import assert from 'node:assert/strict';
import fs from 'node:fs';

const adapter=fs.readFileSync('web/mta-production-state-adapter-v1.js','utf8');
const commands=fs.readFileSync('web/mta-domain-commands-v2.js','utf8');
const runtime=fs.readFileSync('web/mta-app-runtime-full.js','utf8');
const index=fs.readFileSync('web/index.html','utf8');
const api=fs.readFileSync('supabase/functions/mta-api/index.ts','utf8');
const foundation=fs.readFileSync('supabase/migrations/20260921060500_mta_deteni_production_activation_foundation.sql','utf8');
const rbac=fs.readFileSync('supabase/migrations/20260921070000_mta_production_auth_rbac_v1.sql','utf8');
const stateKernel=fs.readFileSync('web/mta-state-kernel-v1.js','utf8');
const grants=fs.readFileSync('supabase/migrations/20261001071000_mta_p97_service_role_dml_grants_v1.sql','utf8');

assert.match(foundation,/create table if not exists public\.mta_detainees/);
assert.match(foundation,/metadata jsonb not null default '\{\}'::jsonb/);
assert.match(grants,/grant select, insert, update, delete on table/);
assert.match(grants,/public\.mta_detainees/);
assert.match(grants,/to service_role/);
assert.match(rbac,/create policy mta_detainees_select_auth/);
assert.match(rbac,/create policy mta_detainees_insert_editor/);
assert.match(rbac,/create policy mta_detainees_update_editor/);

assert.match(api,/if\(req\.method==="POST"\)/);
assert.match(api,/mta_execute_idempotent_mutation/);
assert.match(api,/p_where:req\.method==="POST"\?\{\}:\{id\}/);
assert.match(api,/const table=resource==="audit"\?"mta_audit_events":"mta_"\+resource/);
assert.match(api,/\["blocks","rooms","detainees"\]\.includes\(resource\)/);
assert.match(api,/resource==="detainees"/);
assert.match(api,/body=\{\.\.\.body,scope_id:canonicalScopeId\}/);
assert.match(api,/DETAINEE_NOT_FOUND/);
assert.match(api,/WRONG_SCOPE/);

assert.match(adapter,/mapDetainee/);
assert.match(adapter,/metadata\.gender/);
assert.match(adapter,/metadata\.dateOfBirth/);
assert.match(adapter,/metadata\.passportNumber/);
assert.match(adapter,/metadata\.notes/);
assert.match(adapter,/PRODUCTION_MUTATIONS_ENABLED=false/);
assert.match(adapter,/async function writeAudit/);
assert.match(adapter,/admin-config/);
assert.match(adapter,/isProductionPersistenceEnabled/);
assert.match(adapter,/PRODUCTION_MUTATION_NOT_AUTHORIZED/);
assert.match(adapter,/async function mutateDetainee/);
assert.match(adapter,/async function mutateResource/);
assert.match(adapter,/const path=API\+'\/'/);
assert.match(adapter,/id\?['\"]\/['\"]\+encodeURIComponent\(id\)/);
assert.match(adapter,/request\('detainees',\{method:'POST'/);
assert.match(adapter,/request\('detainees',\{method:'PATCH'/);
assert.match(adapter,/await hydrate\(\)/);

assert.match(commands,/function createDetainee/);
assert.match(commands,/function updateDetainee/);
assert.match(commands,/function archiveDetainee/);
assert.match(commands,/productionDetaineeMutation/);
assert.match(commands,/window\.mtaProductionStateAdapter\?\.isProduction/);
assert.match(commands,/createDetainee,updateDetainee,archiveDetainee/);

assert.match(runtime,/createForm\.onsubmit=async/);
assert.match(runtime,/await command\.createDetainee/);
assert.match(runtime,/await command\.updateDetainee/);
assert.match(runtime,/async function archiveDetainee\(id\)/);
assert.match(runtime,/const idempotencyKey='DETAINEE_ARCHIVE:'\+crypto\.randomUUID\(\)/);
assert.match(runtime,/command\.archiveDetainee\(db,id,\{idempotencyKey\}\)/);
assert.match(runtime,/result\.state/);
assert.match(runtime,/Data tersimpan ke database/);
assert.match(runtime,/mta-production-state-adapter-v1\.js\?v=7/);
assert.match(runtime,/mta-domain-commands-v2\.js\?v=5/);
assert.match(runtime,/mta-state-kernel-v1\.js\?v=5/);
assert.match(runtime,/await window\.MTADeteniDomainCommandsV2\.assignPlacement/);
assert.match(runtime,/await window\.MTADeteniDomainCommandsV2\.advanceLeave/);
assert.match(runtime,/await window\.MTADeteniDomainCommandsV2\?\.createDocument/);

assert.match(index,/mta-production-state-adapter-v1\.js\?v=7/);
assert.match(stateKernel,/isProductionHost/);
assert.match(stateKernel,/PRODUCTION_BROWSER_STORAGE_FORBIDDEN/);
assert.match(stateKernel,/if\(isProductionHost\(\)\)return clone\(window\.__mtaProductionState\|\|\{\}\)/);

assert.match(commands,/async function createLeave/);
assert.match(commands,/async function createBlock/);
assert.match(commands,/async function createRoom/);
assert.match(commands,/async function assignPlacement/);
assert.match(commands,/async function advanceLeave/);
assert.match(commands,/async function createDocument/);
assert.match(commands,/async function transitionDocument/);
assert.match(commands,/async function applyGeneratedDocument/);
assert.match(commands,/async function createDocumentRevision/);
assert.match(commands,/admin-config/);
assert.match(commands,/productionResourceMutation\('leaves'/);
assert.match(commands,/productionResourceMutation\('rooms'/);
assert.match(runtime,/await window\.MTADeteniDomainCommandsV2\.createLeave/);
assert.match(runtime,/mtaProductionStateAdapter\?\.isProduction/);
assert.match(api,/resource==="admin-config"/);
assert.match(api,/resource==="audit-event"/);
console.log('P2 canonical PostgreSQL persistence contract PASS');
console.log('Production path: Command -> API -> Supabase mta_detainees -> DB trigger audit -> hydrate');
console.log('Synthetic path remains localStorage-only and is not used by production runtime.');
