import { strict as assert } from "node:assert";
import fs from "node:fs";
const preview=fs.readFileSync("web/preview-v5.js","utf8");
const movement=fs.readFileSync("web/movement-v9.js","utf8");
const shell=fs.readFileSync("web/mta-unified-shell-v2.js","utf8");
assert.match(preview,/window\.p5openMovement=id=>\{show\('movement'\)/);
assert.match(preview,/p9moveForm select\[name="detaineeId"\]/);
assert.match(movement,/id="p9moveForm"/);
assert.match(movement,/MOVEMENT_CREATE/);
assert.match(movement,/mtaUnifiedAssignPlacement/);
assert.match(shell,/PLACEMENT_ASSIGN/);
assert.match(shell,/PLACEMENT_CAPACITY_BLOCKED/);
console.log("F3_MOVEMENT_ACTION_CONTRACT PASS");
