import assert from 'node:assert/strict';
import fs from 'node:fs';

const api=fs.readFileSync(new URL('../supabase/functions/mta-api/index.ts',import.meta.url),'utf8');
const login=fs.readFileSync(new URL('../supabase/functions/mta-login/index.ts',import.meta.url),'utf8');
const auth=fs.readFileSync(new URL('../web/mta-auth.js',import.meta.url),'utf8');
const authUi=fs.readFileSync(new URL('../web/mta-auth-ui.js',import.meta.url),'utf8');
const users=fs.readFileSync(new URL('../web/user-management-v1.js',import.meta.url),'utf8');
const identity=fs.readFileSync(new URL('../web/identity-security-v1.js',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migrations/20261001090000_mta_nip_identity_contract_v1.sql',import.meta.url),'utf8');
const worker=fs.readFileSync(new URL('../worker-v11.js',import.meta.url),'utf8');

assert.match(migration,/add column if not exists nip text/i);
assert.match(migration,/nip ~ '\^\[0-9\]\{18\}\$'/i);
assert.match(migration,/uq_mta_profiles_nip/i);
assert.match(api,/USER_NIP_INVALID/);
assert.match(api,/USER_NIP_ALREADY_EXISTS/);
assert.match(api,/^.*nip.*\^\\d\{18\}\$.*$/m);
assert.match(login,/mta_profiles/);
assert.match(login,/signInWithPassword/);
assert.match(login,/^.*nip.*\^\\d\{18\}\$.*$/m);
assert.match(worker,/url\.pathname === '\/api\/mta-login'/);
assert.match(worker,/functions\/v1\/mta-login/);
assert.match(worker,/Cache-Control','no-store'/);
assert.match(auth,/api\/mta-login/);
assert.match(auth,/setSession/);
assert.match(authUi,/mtaAuthNip/);
assert.match(authUi,/NIP harus tepat 18 digit/);
assert.doesNotMatch(authUi,/mtaAuthEmail/);
assert.match(authUi,/signIn\(nip,password\)/);
assert.match(users,/name="nip"/);
assert.match(users,/NIP wajib tepat 18 angka/);
assert.match(users,/u\.nip\|\|u\.display_name/);
assert.match(identity,/label>NIP</);
const sampleNip='198008142008011001';
assert.equal(sampleNip.length,18);
assert.equal(sampleNip.slice(0,8),'19800814');
assert.equal(sampleNip.slice(8,14),'200801');
assert.equal(sampleNip.slice(14,15),'1');
assert.equal(sampleNip.slice(15),'001');
console.log('NIP authentication contract: PASS');
