import test from 'node:test';
import assert from 'node:assert/strict';
import { createAtomicGrantHarness } from '../src/runtime/controlled-postgres-concurrency-harness.mjs';

test('P10.125 concurrent consume permits exactly one winner', async () => { const h = createAtomicGrantHarness(); const results = await Promise.all([1,2,3,4].map(() => h.consume({ actorId:'a', scopeId:'s', objectId:'o' }))); assert.equal(results.filter(r => r.affectedRows === 1).length, 1); assert.equal(results.filter(r => r.affectedRows === 0).length, 3); assert.equal(h.snapshot().status, 'CONSUMED'); });
test('P10.126 consume loses to revoke race when revoke commits first', async () => { const h = createAtomicGrantHarness(); const revoked = await h.revoke({ actorId:'a', scopeId:'s' }); const consumed = await h.consume({ actorId:'a', scopeId:'s', objectId:'o' }); assert.equal(revoked.affectedRows,1); assert.equal(consumed.affectedRows,0); assert.equal(h.snapshot().status,'REVOKED'); });
test('P10.127 expired grant cannot consume', async () => { const h = createAtomicGrantHarness({ expiresAt:'2026-09-15T00:59:59.000Z' }); const result = await h.consume({ actorId:'a', scopeId:'s', objectId:'o', at:'2026-09-15T01:00:00.000Z' }); assert.equal(result.affectedRows,0); assert.equal(h.snapshot().status,'ACTIVE'); });
test('P10.128 wrong actor is rejected before transition', async () => { const h=createAtomicGrantHarness(); const result=await h.consume({actorId:'attacker',scopeId:'s',objectId:'o',expectedActorId:'owner'}); assert.equal(result.affectedRows,0); assert.equal(h.snapshot().status,'ACTIVE'); });
test('P10.129 wrong scope is rejected before transition', async () => { const h=createAtomicGrantHarness(); const result=await h.consume({actorId:'a',scopeId:'wrong',objectId:'o',expectedScopeId:'s'}); assert.equal(result.affectedRows,0); assert.equal(h.snapshot().status,'ACTIVE'); });
test('P10.130 wrong object is rejected before transition', async () => { const h=createAtomicGrantHarness(); const result=await h.consume({actorId:'a',scopeId:'s',objectId:'wrong',expectedObjectId:'o'}); assert.equal(result.affectedRows,0); assert.equal(h.snapshot().status,'ACTIVE'); });
test('P10.131 revoke is single-transition under repetition', async () => { const h=createAtomicGrantHarness(); const results=await Promise.all([1,2,3].map(()=>h.revoke({actorId:'a',scopeId:'s'}))); assert.equal(results.filter(r=>r.affectedRows===1).length,1); assert.equal(results.filter(r=>r.affectedRows===0).length,2); assert.equal(h.snapshot().status,'REVOKED'); });
test('P10.132 harness has no database/provider surface', () => { const h=createAtomicGrantHarness(); assert.equal(typeof h.query,'undefined'); assert.equal(typeof h.callProvider,'undefined'); assert.equal(typeof h.transaction,'undefined'); });
