import assert from "node:assert/strict";
import test from "node:test";
import { evaluateFailureMatrix, type FailureMatrix } from "../src/application/p11-681-816-integrated-failure-matrix.js";

const crossDomain = { contractId: "X-001", target: "SYNTHETIC" as const, aggregates: [{ detaineeId: "D-1", detaineeStatus: "ACTIVE" as const, placementId: "R-A", placementState: "RETURNED" as const, headcountIncluded: true }], reconciliation: { contractId: "R-1", target: "SYNTHETIC" as const, observations: [{ checkpoint: "P11.681", detaineeId: "D-1", placement: { detaineeId: "D-1", placementId: "R-A", state: "RETURNED" as const }, movementEvents: [{ eventId: "M-1", detaineeId: "D-1", fromPlacementId: null, toPlacementId: "R-A", kind: "TEMPORARY_EXIT_RETURN" as const, headcountDelta: 1 }], expectedHeadcount: 1, observedHeadcount: 1 }] } };
const report = { snapshotId: "S-1", readModelGeneratedAt: "2026-09-15T10:00:00Z", expectedActiveCount: 1, reportedActiveCount: 1, report: { reportId: "R-1", reportDate: "2026-09-15", shift: "PAGI" as const, teamName: "SYN-B", generatedAt: "2026-09-15T10:00:00Z", sourceSnapshotId: "S-1", sections: ["IDENTITAS_LAPORAN","PERSONEL_REGU","KONDISI_DETENI","KEGIATAN_JAGA","KEJADIAN_PENTING","SERAH_TERIMA","PENGESAHAN"].map((code) => ({ code, title: code, rows: [{ label: "x", value: "synthetic", provenance: "OPERATIONAL_READ_MODEL" as const }] })) } };

test("P11.681-816 accepts all-green synthetic scenario", () => { const matrix: FailureMatrix = { matrixId: "FM-1", target: "SYNTHETIC", scenarios: [{ id: "GREEN", crossDomain, report, expected: "READY" }] }; assert.equal(evaluateFailureMatrix(matrix), "READY"); });
test("P11.681-816 requires expected block on snapshot drift", () => { const matrix: FailureMatrix = { matrixId: "FM-2", target: "SYNTHETIC", scenarios: [{ id: "DRIFT", crossDomain, report: { ...report, snapshotId: "S-2" }, expected: "BLOCKED" }] }; assert.equal(evaluateFailureMatrix(matrix), "READY"); });
test("P11.681-816 blocks wrong expected outcome", () => { const matrix: FailureMatrix = { matrixId: "FM-3", target: "SYNTHETIC", scenarios: [{ id: "WRONG", crossDomain, report, expected: "BLOCKED" }] }; assert.equal(evaluateFailureMatrix(matrix), "BLOCKED"); });
