import { strict as assert } from "node:assert";
import { test } from "node:test";
import { integratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationCheckpoints, createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode, replayIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode, certifyIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode, resetIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationReplayRegistry } from "../src/application/p13-218881-232880-integrated-integrity-audit-terminal-closure-certification-seal-receipt-attestation.ts";

const base = { artifactId:"artifact-001", parentArtifactId:"artifact-parent-001", decisionFingerprint:"decision-fp-001", closureArtifactId:"artifact-parent-001", closureDecisionFingerprint:"closure-fp-001", auditArtifactId:"audit-001", auditDecisionFingerprint:"decision-fp-001", certificationArtifactId:"certification-001", certificationDecisionFingerprint:"certification-fp-001", sealArtifactId:"seal-001", sealDecisionFingerprint:"seal-fp-001", receiptArtifactId:"receipt-001", receiptDecisionFingerprint:"receipt-fp-001", attestationArtifactId:"attestation-001", attestationDecisionFingerprint:"attestation-fp-001" };

test("P13.218881-232880 contains exactly 100 unique sequential checkpoints",()=>{ const c=integratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationCheckpoints(); assert.equal(c.length,100); assert.equal(new Set(c).size,100); assert.equal(c[0],"P13.218881-219040"); assert.equal(c[99],"P13.232741-232880"); for(let i=1;i<c.length;i++) assert.equal(Number(c[i].match(/P13\.(\\d+)-/)?.[1]),218881+i*140); });
test("attestation layer is immutable synthetic review-only",()=>{ const n=createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.218881-219040"}); assert.equal(n.state,"TERMINAL_CLOSURE_CERTIFICATION_SEAL_RECEIPT_ATTESTATION_VERIFIED_FOR_REVIEW"); assert.equal(Object.isFrozen(n),true); assert.equal(n.syntheticOnly,true); assert.equal(n.authorizationGranted,false); assert.equal(n.dispatchApproved,false); assert.equal(n.externalTransportRequested,false); assert.equal(n.dispatchExecuted,false); assert.equal(n.durablePublicationCreated,false); });
test("replay is deterministic and fingerprint drift conflicts",()=>{ resetIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationReplayRegistry(); const n=createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.221681-221840"}); assert.equal(replayIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode(n),"ADMIT"); assert.equal(replayIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode(n),"REPLAY"); assert.equal(replayIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...n,decisionFingerprint:"decision-fp-drift"}),"CONFLICT"); });
test("certification remains fail-closed",()=>{ resetIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationReplayRegistry(); const n=createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.232741-232880"}); const c=certifyIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode(n); assert.equal(c.certified,true); assert.equal(c.replayDisposition,"ADMIT"); assert.equal(c.syntheticOnly,true); assert.equal(c.dispatchExecuted,false); });
test("continuity mismatches fail closed",()=>{ assert.throws(()=>createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.218881-219040",closureArtifactId:"wrong-parent"})); assert.throws(()=>createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.218881-219040",certificationArtifactId:"audit-001"})); assert.throws(()=>createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.218881-219040",sealArtifactId:"certification-001"})); assert.throws(()=>createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.218881-219040",receiptArtifactId:"seal-001"})); assert.throws(()=>createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.218881-219040",attestationArtifactId:"receipt-001"})); assert.throws(()=>createIntegratedIntegrityAuditTerminalClosureCertificationSealReceiptAttestationNode({...base,checkpoint:"P13.218881-219040",attestationDecisionFingerprint:"decision-fp-001"})); });
