import {strict as assert} from "node:assert";
import {test} from "node:test";
import {p13AttestationClosureCheckpoints,createP13AttestationClosureNode,replayP13AttestationClosureNode,certifyP13AttestationClosureNode,resetP13AttestationClosureReplayRegistry} from "../src/application/p13-232881-246880-attestation-closure.ts";
const base={artifactId:"artifact-002",parentArtifactId:"artifact-parent-002",decisionFingerprint:"decision-fp-002",attestationArtifactId:"attestation-002",attestationDecisionFingerprint:"attestation-fp-002"};
test("P13.232881-246880 has exactly 100 sequential checkpoints",()=>{const c=p13AttestationClosureCheckpoints();assert.equal(c.length,100);assert.equal(new Set(c).size,100);assert.equal(c[0],"P13.232881-233040");assert.equal(c[99],"P13.246741-246880");for(let i=1;i<c.length;i++){const m=c[i].match(/^P13\.(\d+)-/);assert.ok(m);assert.equal(Number(m[1]),232881+i*140);}});
test("closure is immutable synthetic review-only",()=>{const n=createP13AttestationClosureNode({...base,checkpoint:"P13.232881-233040"});assert.equal(Object.isFrozen(n),true);assert.equal(n.syntheticOnly,true);assert.equal(n.authorizationGranted,false);assert.equal(n.dispatchApproved,false);assert.equal(n.externalTransportRequested,false);assert.equal(n.dispatchExecuted,false);assert.equal(n.durablePublicationCreated,false);});
test("replay is deterministic and drift conflicts",()=>{resetP13AttestationClosureReplayRegistry();const n=createP13AttestationClosureNode({...base,checkpoint:"P13.239881-240040"});assert.equal(replayP13AttestationClosureNode(n),"ADMIT");assert.equal(replayP13AttestationClosureNode(n),"REPLAY");assert.equal(replayP13AttestationClosureNode({...n,decisionFingerprint:"drift"}),"CONFLICT");});
test("certification remains fail-closed",()=>{resetP13AttestationClosureReplayRegistry();const n=createP13AttestationClosureNode({...base,checkpoint:"P13.246741-246880"});const c=certifyP13AttestationClosureNode(n);assert.equal(c.certified,true);assert.equal(c.syntheticOnly,true);assert.equal(c.dispatchExecuted,false);});
test("identity aliasing fails closed",()=>{assert.throws(()=>createP13AttestationClosureNode({...base,checkpoint:"P13.232881-233040",attestationArtifactId:"artifact-002"}));assert.throws(()=>createP13AttestationClosureNode({...base,checkpoint:"P13.232881-233040",attestationArtifactId:"artifact-parent-002"}));assert.throws(()=>createP13AttestationClosureNode({...base,checkpoint:"P13.232881-233040",attestationDecisionFingerprint:"decision-fp-002"}));});
