import { strict as assert } from "node:assert";
import { test } from "node:test";
import { createIntegratedIntegrityAuditCertificationNode, replayIntegratedIntegrityAuditCertificationNode, certifyIntegratedIntegrityAuditCertificationNode, resetIntegratedIntegrityAuditCertificationReplayRegistry, integratedIntegrityAuditCertificationCheckpoints } from "../src/application/p13-67561-70240-integrated-integrity-audit-certification.js";
import { integratedIntegrityAuditCertificationBCheckpoints } from "../src/application/p13-70241-72920-integrated-integrity-audit-certification-b.js";
import { integratedIntegrityAuditCertificationCCheckpoints } from "../src/application/p13-72921-75600-integrated-integrity-audit-certification-c.js";
import { integratedIntegrityAuditCertificationDCheckpoints } from "../src/application/p13-75601-78240-integrated-integrity-audit-certification-d.js";
import { integratedIntegrityAuditCertificationECheckpoints } from "../src/application/p13-78241-80920-integrated-integrity-audit-certification-e.js";

test("P13.67561-80920 registers exactly 100 unique checkpoints",()=>{const all=[...integratedIntegrityAuditCertificationCheckpoints(),...integratedIntegrityAuditCertificationBCheckpoints(),...integratedIntegrityAuditCertificationCCheckpoints(),...integratedIntegrityAuditCertificationDCheckpoints(),...integratedIntegrityAuditCertificationECheckpoints()];assert.equal(all.length,100);assert.equal(new Set(all).size,100);assert.equal(all[0],"P13.67561-67720");assert.equal(all[99],"P13.80801-80920");});

test("integrated certification binds preceding artifact and audit fingerprint, with deterministic replay",()=>{resetIntegratedIntegrityAuditCertificationReplayRegistry();const node=createIntegratedIntegrityAuditCertificationNode({checkpoint:"P13.67561-67720",artifactId:"artifact-202",parentArtifactId:"artifact-201",decisionFingerprint:"fp-202",precedingArtifactId:"artifact-201",precedingDecisionFingerprint:"fp-201",auditArtifactId:"audit-201",auditDecisionFingerprint:"fp-202"});assert.equal(Object.isFrozen(node),true);assert.equal(node.state,"CERTIFIED_INTEGRITY_AUDIT_FOR_REVIEW");assert.equal(replayIntegratedIntegrityAuditCertificationNode(node),"ADMIT");assert.equal(replayIntegratedIntegrityAuditCertificationNode(node),"REPLAY");const conflict={...node,decisionFingerprint:"fp-drift",auditDecisionFingerprint:"fp-drift"} as typeof node;assert.equal(replayIntegratedIntegrityAuditCertificationNode(conflict),"CONFLICT");assert.equal(certifyIntegratedIntegrityAuditCertificationNode(node).certified,true);assert.equal(node.authorizationGranted,false);assert.equal(node.dispatchApproved,false);assert.equal(node.externalTransportRequested,false);assert.equal(node.dispatchExecuted,false);assert.equal(node.durablePublicationCreated,false);assert.equal(node.syntheticOnly,true);});

test("continuity mismatch fails closed",()=>{assert.throws(()=>createIntegratedIntegrityAuditCertificationNode({checkpoint:"P13.67561-67720",artifactId:"artifact-203",parentArtifactId:"artifact-201",decisionFingerprint:"fp-203",precedingArtifactId:"artifact-wrong",precedingDecisionFingerprint:"fp-201",auditArtifactId:"audit-202",auditDecisionFingerprint:"fp-203"}),/continuity mismatch/);});
