import assert from "node:assert/strict";
import test from "node:test";
import type { LocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionCertification } from "../src/application/local-runtime-recovery-operational-audit-publication-dispatch-authorization-decision-certification.js";
import type { LocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityCertification } from "../src/application/local-runtime-recovery-operational-audit-publication-dispatch-authorization-decision-evidence-closure-integrity-certification.js";
import type { LocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptCertification } from "../src/application/local-runtime-recovery-operational-audit-publication-dispatch-authorization-decision-evidence-closure-integrity-receipt-certification.js";
import type { LocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureCertification } from "../src/application/local-runtime-recovery-operational-audit-publication-dispatch-authorization-decision-evidence-closure-integrity-receipt-closure-certification.js";
import { createLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity } from "../src/application/local-runtime-recovery-operational-audit-publication-dispatch-authorization-decision-evidence-closure-integrity-receipt-closure-integrity.js";
import { replayLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity, resetLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrityReplayRegistry } from "../src/application/local-runtime-recovery-operational-audit-publication-dispatch-authorization-decision-evidence-closure-integrity-receipt-closure-integrity-replay.js";
import { certifyLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity } from "../src/application/local-runtime-recovery-operational-audit-publication-dispatch-authorization-decision-evidence-closure-integrity-receipt-closure-integrity-certification.js";

const decisionCertification = { certificationId:"DEC-C",decisionId:"DEC",authorizationCertificationId:"AUTH-C",authorizationId:"AUTH",candidateId:"CAND",requestId:"REQ",publicationCertificationId:"PUB-C",publicationId:"PUB",decisionFingerprint:"FP",decisionState:"REVIEW_REQUIRED",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,syntheticOnly:true,replayDisposition:"ADMIT",certified:true } as const as LocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionCertification;
const integrityCertification = { certificationId:"INT-C",integrityId:"INT",closureCertificationId:"CLOSE-C",closureId:"CLOSE",decisionCertificationId:"DEC-C",decisionId:"DEC",authorizationCertificationId:"AUTH-C",authorizationId:"AUTH",candidateId:"CAND",requestId:"REQ",publicationCertificationId:"PUB-C",publicationId:"PUB",decisionFingerprint:"FP",integrityState:"VERIFIED_TERMINAL_REVIEW_ARTIFACT",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true,replayDisposition:"ADMIT",certified:true } as const as LocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityCertification;
const receiptCertification = { certificationId:"RCPT-C",integrityCertificationId:"INT-C",integrityId:"INT",closureCertificationId:"CLOSE-C",closureId:"CLOSE",decisionCertificationId:"DEC-C",decisionId:"DEC",decisionFingerprint:"FP",receiptState:"RECEIVED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true,replayDisposition:"ADMIT",certified:true } as const as LocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptCertification;
const closureCertification = { certificationId:"RCLOSE-C",receiptCertificationId:"RCPT-C",receiptId:"RCPT",integrityCertificationId:"INT-C",integrityId:"INT",closureId:"RCLOSE",decisionCertificationId:"DEC-C",decisionId:"DEC",decisionFingerprint:"FP",evidenceClosureIntegrityReceiptClosureState:"CLOSED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true,replayDisposition:"ADMIT",certified:true } as const as LocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureCertification;

test("P13.19481-19600: receipt closure integrity replay is deterministic", () => {
  resetLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrityReplayRegistry();
  const integrity = createLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity({ integrityId:"RCLOSE-INT", closureCertification, receiptCertification, integrityCertification, decisionCertification });
  assert.equal(replayLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity({ integrity, closureCertification, receiptCertification, integrityCertification, decisionCertification }), "ADMIT");
  assert.equal(replayLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity({ integrity, closureCertification, receiptCertification, integrityCertification, decisionCertification }), "REPLAY");
  assert.throws(() => replayLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity({ integrity:{ ...integrity, decisionFingerprint:"DRIFT" }, closureCertification, receiptCertification, integrityCertification, decisionCertification }), /drift/i);
});

test("P13.19601-19720: integrated certification remains review-only and fail-closed", () => {
  resetLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrityReplayRegistry();
  const integrity = createLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity({ integrityId:"RCLOSE-INT-CERT", closureCertification, receiptCertification, integrityCertification, decisionCertification });
  const certified = certifyLocalRuntimeRecoveryOperationalAuditPublicationDispatchAuthorizationDecisionEvidenceClosureIntegrityReceiptClosureIntegrity({ certificationId:"RCLOSE-INT-CERTIFICATION", integrity, closureCertification, receiptCertification, integrityCertification, decisionCertification });
  assert.equal(certified.certified, true);
  assert.equal(certified.syntheticOnly, true);
  assert.equal(certified.authorizationGranted, false);
  assert.equal(certified.dispatchApproved, false);
  assert.equal(certified.dispatchExecuted, false);
  assert.equal(certified.externalTransportRequested, false);
  assert.equal(certified.durablePublicationCreated, false);
});
