import assert from 'node:assert/strict';
import fs from 'node:fs';
const migration=fs.readFileSync('supabase/migrations/20260921060500_mta_deteni_production_activation_foundation.sql','utf8');
const rbac=fs.readFileSync('supabase/migrations/20260921070000_mta_production_auth_rbac_v1.sql','utf8');
const edge=fs.readFileSync('supabase/functions/mta-api/index.ts','utf8');
const client=fs.readFileSync('web/mta-production-api.js','utf8');
assert.match(rbac,/create table if not exists public\.mta_profiles/);
assert.match(rbac,/check \(role in \('OWNER','ADMIN','EDITOR','REVIEWER','AUDITOR','VIEWER'\)\)/);
assert.match(rbac,/alter table public\.mta_profiles enable row level security/);
assert.match(rbac,/mta_detainees_insert_editor/);
assert.match(rbac,/mta_detainees_delete_admin/);
assert.match(rbac,/mta_audit_row_change/);
assert.match(edge,/supabase\.auth\.getUser\(\)/);
assert.match(edge,/RBAC_WRITE_DENIED/);
assert.match(edge,/mta_detainees/);
assert.match(client,/mtaProductionApi/);
console.log('Production Auth/RBAC API contract PASS');
