import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read = file => readFile(new URL(`../web/${file}`, import.meta.url), "utf8");

test("QR camera is wired to the operational Scan Center", async () => {
  const camera = await read("qr-camera-v2.js");
  const preview = await read("preview-v5.js");
  const worker = await read("../worker-v11.js");

  assert.match(camera, /querySelector\('#p5scanin'\)/);
  assert.match(camera, /window\.show\('p5scan'\)/);
  assert.match(camera, /window\.p5resolve\(\)/);
  assert.match(camera, /mta:qr-detected/);

  assert.match(preview, /window\.p5resolve/);
  assert.match(preview, /window\.p5openDetainee/);
  assert.match(preview, /window\.p5openMovement/);
  assert.match(preview, /SCAN_ACTION_OPEN_DETAINEE/);
  assert.match(preview, /SCAN_ACTION_MOVEMENT/);

  const cameraIndex = worker.indexOf('/qr-camera-v2.js');
  const previewIndex = worker.indexOf('/preview-v5.js');
  const mobileIndex = worker.indexOf('/mobile-shell-v1.js');
  assert.ok(cameraIndex >= 0 && previewIndex >= 0 && mobileIndex >= 0);
  assert.ok(cameraIndex < previewIndex, "camera adapter must load before Scan Center");
  assert.ok(previewIndex < mobileIndex, "Scan Center must load before mobile shell");
});

test("QR generated by the preview has a resolvable synthetic protocol", async () => {
  const preview = await read("preview-v5.js");
  assert.match(preview, /mta:\/\/\$\{kind\}\/\$\{q\.token\}/);
  assert.match(preview, /raw\.startsWith\('mta:\/\/detainee\/'\)/);
  assert.match(preview, /raw\.startsWith\('mta:\/\/room\/'\)/);
});
