import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read = file => readFile(new URL(`../web/${file}`, import.meta.url), "utf8");

test("QR camera is wired to the operational Scan Center", async () => {
  const camera = await read("qr-camera-v2.js");
  const preview = await read("preview-v5.js");
  const runtime = await read("mta-app-runtime-full.js");
  const runtime = await read("mta-app-runtime-full.js");
  const print = await read("qr-print-clean-v3.js");

  assert.match(camera, /querySelector\('#p5scanin'\)/);
  assert.match(camera, /window\.show\('p5scan'\)/);
  assert.match(camera, /window\.p5resolve\(\)/);
  assert.match(camera, /mta:qr-detected/);

  assert.match(preview, /window\.p5resolve/);
  assert.match(preview, /window\.p5openDetainee/);
  assert.match(preview, /window\.p5openMovement/);
  assert.match(preview, /SCAN_ACTION_OPEN_DETAINEE/);
  assert.match(preview, /SCAN_ACTION_MOVEMENT/);

  const cameraIndex = runtime.indexOf('/qr-camera-v2.js');
  const previewIndex = runtime.indexOf('/preview-v5.js');
  const mobileIndex = runtime.indexOf('/mobile-shell-v1.js');
  assert.ok(cameraIndex >= 0 && previewIndex >= 0 && mobileIndex >= 0);
  assert.ok(cameraIndex < previewIndex, "camera adapter must load before Scan Center");
  assert.ok(previewIndex < mobileIndex, "Scan Center must load before mobile shell");
});

test("QR generated by the preview has a resolvable synthetic protocol", async () => {
  const preview = await read("preview-v5.js");
  const worker = await read("../worker-v11.js");
  const print = await read("qr-print-clean-v3.js");
  assert.match(preview, /mta:\/\/\$\{kind\}\/\$\{id\}\/\$\{q\.token\}/);
  assert.match(preview, /raw\.startsWith\('mta:\/\/detainee\/'\)/);
  assert.match(preview, /raw\.startsWith\('mta:\/\/room\/'\)/);
  assert.ok(preview.includes('const resourceId=parts.length>=4?parts[parts.length-2]'));
  assert.match(print, /const payload='mta:\/\/'\+kind\+'\/'\+id\+'\/'\+q\.token/);
  assert.match(print, /\.qr svg\{width:7[68]mm!important;height:7[68]mm!important/);
  assert.doesNotMatch(print, /<div class="brand">MTA DETENI<\/div>/);
  assert.doesNotMatch(print, /<div class="primary">/);
  assert.match(runtime, /qr-print-clean-v3\.js\?v=5/);
});
