import { readFileSync } from 'node:fs';
import { strict as assert } from 'node:assert';
const s=readFileSync(new URL('../web/user-management-v1.js',import.meta.url),'utf8');
const api=readFileSync(new URL('../web/mta-production-api.js',import.meta.url),'utf8');
const apiServer=readFileSync(new URL('../supabase/functions/mta-api/index.ts',import.meta.url),'utf8');
const i=readFileSync(new URL('../web/index.html',import.meta.url),'utf8');
const reg=readFileSync(new URL('../FEATURE_REGISTRY.md',import.meta.url),'utf8');

assert.match(s,/MTAUserManagementView/);
assert.match(s,/user-management/);
assert.match(s,/admin-users/);
assert.match(s,/OWNER/);
assert.match(s,/ADMIN/);
assert.match(s,/EDITOR/);
assert.match(s,/REVIEWER/);
assert.match(s,/AUDITOR/);
assert.match(s,/VIEWER/);
assert.match(s,/ROLE_SCOPE/);
assert.match(s,/Password minimal 12/);
assert.match(s,/tidak disimpan/);
assert.match(s,/window\.MTADeteniStateKernel\.audit/);
assert.match(s,/mta:unified-ready/);
assert.match(i,/user-management-v1\.js/);
assert.match(api,/create:\(resource,body\)=>request\(resource,\{method:'POST',body\}\)/);
assert.match(api,/update:\(resource,id,body\)=>request\(resource,\{method:'PATCH',id,body\}\)/);
assert.match(apiServer,/resource==="admin-users"/);
assert.match(apiServer,/new Set\(\["OWNER","ADMIN"\]\)/);
assert.match(apiServer,/SUPABASE_SERVICE_ROLE_KEY/);
assert.match(apiServer,/auth\.admin\.createUser/);
assert.match(apiServer,/mta_profiles/);
assert.match(apiServer,/USER_CREATE/);
assert.match(apiServer,/SELF_DISABLE_FORBIDDEN/);
assert.match(apiServer,/SELF_ROLE_CHANGE_FORBIDDEN/);
assert.match(apiServer,/OWNER_USER_MANAGEMENT_DENIED/);
assert.match(apiServer,/role==="OWNER"\?\(profiles\|\|\[\]\):(profiles\|\|\[\]\)\.filter/);
assert.match(s,/currentRole\(\)===\"OWNER\"\?allRows:allRows\.filter/);
assert.match(s,/Akun OWNER tidak dapat dilihat atau dikelola/);
assert.match(reg,/MTA-F-20260927-021/);
console.log('MTA-F-20260927-021 User Management / Tambah User contract: PASS');
