export type TerminalEvidenceContinuationJDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceContinuationJNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.51601-51760","P13.51761-51880","P13.51881-52000","P13.52001-52160","P13.52161-52280","P13.52281-52400","P13.52401-52560","P13.52561-52680","P13.52681-52800","P13.52801-52960","P13.52961-53080","P13.53081-53200","P13.53201-53360","P13.53361-53480","P13.53481-53600","P13.53601-53760","P13.53761-53880","P13.53881-54000","P13.54001-54160","P13.54161-54280"] as const);
export function terminalEvidenceContinuationJCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationJNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationJNode["state"]}):TerminalEvidenceContinuationJNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation J checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation J identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationJNode(node:TerminalEvidenceContinuationJNode):TerminalEvidenceContinuationJDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation J node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationJNode(node:TerminalEvidenceContinuationJNode):Readonly<TerminalEvidenceContinuationJNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationJDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationJNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation J replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationJReplayRegistry():void{registry.clear();}
