export type TerminalEvidenceContinuationHDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceContinuationHNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.46241-46400","P13.46401-46520","P13.46521-46640","P13.46641-46800","P13.46801-46920","P13.46921-47040","P13.47041-47200","P13.47201-47320","P13.47321-47440","P13.47441-47600","P13.47601-47720","P13.47721-47840","P13.47841-48000","P13.48001-48120","P13.48121-48240","P13.48241-48400","P13.48401-48520","P13.48521-48640","P13.48641-48800","P13.48801-48920"] as const);
export function terminalEvidenceContinuationHCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationHNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationHNode["state"]}):TerminalEvidenceContinuationHNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation H checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation H identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationHNode(node:TerminalEvidenceContinuationHNode):TerminalEvidenceContinuationHDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation H node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationHNode(node:TerminalEvidenceContinuationHNode):Readonly<TerminalEvidenceContinuationHNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationHDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationHNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation H replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationHReplayRegistry():void{registry.clear();}
