export type IntegratedIntegrityAuditTerminalClosureBoundaryDDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureBoundaryDNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_BOUNDARY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.129441-129600","P13.129601-129720","P13.129721-129840","P13.129841-130000","P13.130001-130120","P13.130121-130240","P13.130241-130400","P13.130401-130520","P13.130521-130640","P13.130641-130800","P13.130801-130920","P13.130921-131040","P13.131041-131200","P13.131201-131320","P13.131321-131440","P13.131441-131600","P13.131601-131720","P13.131721-131840","P13.131841-132000","P13.132001-132160"] as const);
export function integratedIntegrityAuditTerminalClosureBoundaryDCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureBoundaryDNode(input:Omit<IntegratedIntegrityAuditTerminalClosureBoundaryDNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureBoundaryDNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure boundary D checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure boundary D identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure boundary D continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_BOUNDARY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureBoundaryDNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryDNode):IntegratedIntegrityAuditTerminalClosureBoundaryDDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure boundary D node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureBoundaryDNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryDNode):Readonly<IntegratedIntegrityAuditTerminalClosureBoundaryDNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureBoundaryDDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureBoundaryDNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure boundary D replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureBoundaryDReplayRegistry():void{registry.clear();}
