export type TerminalEvidenceContinuationEDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceContinuationENode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.38241-38360","P13.38361-38480","P13.38481-38640","P13.38641-38760","P13.38761-38880","P13.38881-39040","P13.39041-39160","P13.39161-39280","P13.39281-39440","P13.39441-39560","P13.39561-39680","P13.39681-39840","P13.39841-39960","P13.39961-40080","P13.40081-40240","P13.40241-40360","P13.40361-40480","P13.40481-40640","P13.40641-40760","P13.40761-40880"] as const);
export function terminalEvidenceContinuationECheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationENode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationENode["state"]}):TerminalEvidenceContinuationENode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation E checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation E identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationENode(node:TerminalEvidenceContinuationENode):TerminalEvidenceContinuationEDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation E node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationENode(node:TerminalEvidenceContinuationENode):Readonly<TerminalEvidenceContinuationENode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationEDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationENode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation E replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationEReplayRegistry():void{registry.clear();}
