export type TerminalEvidenceContinuationCDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceContinuationCNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.32881-33040","P13.33041-33160","P13.33161-33280","P13.33281-33440","P13.33441-33560","P13.33561-33680","P13.33681-33840","P13.33841-33960","P13.33961-34080","P13.34081-34240","P13.34241-34360","P13.34361-34480","P13.34481-34640","P13.34641-34760","P13.34761-34880","P13.34881-35040","P13.35041-35160","P13.35161-35280","P13.35281-35440","P13.35441-35560"] as const);
export function terminalEvidenceContinuationCCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationCNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationCNode["state"]}):TerminalEvidenceContinuationCNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation C checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation C identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationCNode(node:TerminalEvidenceContinuationCNode):TerminalEvidenceContinuationCDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation C node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationCNode(node:TerminalEvidenceContinuationCNode):Readonly<TerminalEvidenceContinuationCNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationCDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationCNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation C replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationCReplayRegistry():void{registry.clear();}
