export type IntegratedIntegrityAuditTerminalClosureCDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureCNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.113121-113280","P13.113281-113400","P13.113401-113520","P13.113521-113680","P13.113681-113800","P13.113801-113920","P13.113921-114080","P13.114081-114200","P13.114201-114320","P13.114321-114480","P13.114481-114600","P13.114601-114720","P13.114721-114880","P13.114881-115000","P13.115001-115120","P13.115121-115280","P13.115281-115400","P13.115401-115520","P13.115521-115680","P13.115681-115840"] as const);
export function integratedIntegrityAuditTerminalClosureCCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureCNode(input:Omit<IntegratedIntegrityAuditTerminalClosureCNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureCNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure C checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure C identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure C continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureCNode(node:IntegratedIntegrityAuditTerminalClosureCNode):IntegratedIntegrityAuditTerminalClosureCDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure C node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureCNode(node:IntegratedIntegrityAuditTerminalClosureCNode):Readonly<IntegratedIntegrityAuditTerminalClosureCNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureCDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureCNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure C replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureCReplayRegistry():void{registry.clear();}
