export type TerminalEvidenceIntegrityAuditDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceIntegrityAuditNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"AUDITED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.54281-54400","P13.54401-54520","P13.54521-54640","P13.54641-54800","P13.54801-54920","P13.54921-55040","P13.55041-55200","P13.55201-55320","P13.55321-55440","P13.55441-55600","P13.55601-55720","P13.55721-55840","P13.55841-56000","P13.56001-56120","P13.56121-56240","P13.56241-56400","P13.56401-56520","P13.56521-56640","P13.56641-56800","P13.56801-56960"] as const);
export function terminalEvidenceIntegrityAuditCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceIntegrityAuditNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string}):TerminalEvidenceIntegrityAuditNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence integrity audit checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence integrity audit identity is incomplete.");return Object.freeze({...input,state:"AUDITED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceIntegrityAuditNode(node:TerminalEvidenceIntegrityAuditNode):TerminalEvidenceIntegrityAuditDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence integrity audit node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceIntegrityAuditNode(node:TerminalEvidenceIntegrityAuditNode):Readonly<TerminalEvidenceIntegrityAuditNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceIntegrityAuditDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceIntegrityAuditNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence integrity audit replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceIntegrityAuditReplayRegistry():void{registry.clear();}
