export type IntegratedIntegrityAuditTerminalClosureBoundaryBDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureBoundaryBNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_BOUNDARY_B_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.134881-135040","P13.135041-135160","P13.135161-135320","P13.135321-135440","P13.135441-135600","P13.135601-135720","P13.135721-135880","P13.135881-136000","P13.136001-136160","P13.136161-136280","P13.136281-136440","P13.136441-136560","P13.136561-136720","P13.136721-136840","P13.136841-137000","P13.137001-137120","P13.137121-137280","P13.137281-137400","P13.137401-137560","P13.137561-137680"] as const);
export function integratedIntegrityAuditTerminalClosureBoundaryBCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureBoundaryBNode(input:Omit<IntegratedIntegrityAuditTerminalClosureBoundaryBNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureBoundaryBNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure boundary B checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure boundary B identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure boundary B continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_BOUNDARY_B_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureBoundaryBNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryBNode):IntegratedIntegrityAuditTerminalClosureBoundaryBDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure boundary B node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureBoundaryBNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryBNode):Readonly<IntegratedIntegrityAuditTerminalClosureBoundaryBNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureBoundaryBDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureBoundaryBNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure boundary B replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureBoundaryBReplayRegistry():void{registry.clear();}
