export type TerminalEvidenceContinuationADisposition = "ADMIT" | "REPLAY" | "CONFLICT";
export type TerminalEvidenceContinuationANode = Readonly<{ checkpoint: string; artifactId: string; parentArtifactId: string; decisionFingerprint: string; state: "CLOSED_FOR_REVIEW" | "VERIFIED_FOR_REVIEW" | "READY_FOR_REVIEW"; authorizationGranted: false; dispatchApproved: false; externalTransportRequested: false; dispatchExecuted: false; durablePublicationCreated: false; syntheticOnly: true }>;
const registry = new Map<string, string>();
const CHECKPOINTS = Object.freeze([
"P13.27561-27680","P13.27681-27840","P13.27841-27960","P13.27961-28080","P13.28081-28240","P13.28241-28360","P13.28361-28480","P13.28481-28640","P13.28641-28760","P13.28761-28880","P13.28881-29040","P13.29041-29160","P13.29161-29280","P13.29281-29440","P13.29441-29560","P13.29561-29680","P13.29681-29840","P13.29841-29960","P13.29961-30080","P13.30081-30240"
] as const);
export function terminalEvidenceContinuationACheckpoints(): readonly string[] { return CHECKPOINTS; }
export function createTerminalEvidenceContinuationANode(input: { checkpoint: string; artifactId: string; parentArtifactId: string; decisionFingerprint: string; state: TerminalEvidenceContinuationANode["state"] }): TerminalEvidenceContinuationANode { if (!(CHECKPOINTS as readonly string[]).includes(input.checkpoint)) throw new Error("Unsupported terminal evidence continuation A checkpoint."); if (!input.artifactId.trim() || !input.parentArtifactId.trim() || !input.decisionFingerprint.trim()) throw new Error("Terminal evidence continuation A identity is incomplete."); return Object.freeze({ ...input, authorizationGranted:false, dispatchApproved:false, externalTransportRequested:false, dispatchExecuted:false, durablePublicationCreated:false, syntheticOnly:true }); }
export function replayTerminalEvidenceContinuationANode(node: TerminalEvidenceContinuationANode): TerminalEvidenceContinuationADisposition { if (!node.syntheticOnly || node.authorizationGranted || node.dispatchApproved || node.externalTransportRequested || node.dispatchExecuted || node.durablePublicationCreated) throw new Error("Terminal evidence continuation A node is executable or invalid."); const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`; const previous=registry.get(key); if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";} return previous===node.decisionFingerprint?"REPLAY":"CONFLICT"; }
export function certifyTerminalEvidenceContinuationANode(node: TerminalEvidenceContinuationANode): Readonly<TerminalEvidenceContinuationANode & { certified:true; replayDisposition:Exclude<TerminalEvidenceContinuationADisposition,"CONFLICT"> }> { const replayDisposition=replayTerminalEvidenceContinuationANode(node); if(replayDisposition==="CONFLICT") throw new Error("Terminal evidence continuation A replay conflict."); return Object.freeze({...node,certified:true,replayDisposition}); }
export function resetTerminalEvidenceContinuationAReplayRegistry(): void { registry.clear(); }
