export type IntegratedIntegrityAuditTerminalClosureBoundaryBDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureBoundaryBNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_BOUNDARY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.124001-124160","P13.124161-124280","P13.124281-124400","P13.124401-124560","P13.124561-124680","P13.124681-124800","P13.124801-124960","P13.124961-125080","P13.125081-125200","P13.125201-125360","P13.125361-125480","P13.125481-125600","P13.125601-125760","P13.125761-125880","P13.125881-126000","P13.126001-126160","P13.126161-126280","P13.126281-126400","P13.126401-126560","P13.126561-126720"] as const);
export function integratedIntegrityAuditTerminalClosureBoundaryBCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureBoundaryBNode(input:Omit<IntegratedIntegrityAuditTerminalClosureBoundaryBNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureBoundaryBNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure boundary B checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure boundary B identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure boundary B continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_BOUNDARY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureBoundaryBNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryBNode):IntegratedIntegrityAuditTerminalClosureBoundaryBDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure boundary B node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureBoundaryBNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryBNode):Readonly<IntegratedIntegrityAuditTerminalClosureBoundaryBNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureBoundaryBDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureBoundaryBNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure boundary B replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureBoundaryBReplayRegistry():void{registry.clear();}
