export type IntegratedIntegrityAuditTerminalClosureDDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureDNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.115841-116000","P13.116001-116120","P13.116121-116240","P13.116241-116400","P13.116401-116520","P13.116521-116640","P13.116641-116800","P13.116801-116920","P13.116921-117040","P13.117041-117200","P13.117201-117320","P13.117321-117440","P13.117441-117600","P13.117601-117720","P13.117721-117840","P13.117841-118000","P13.118001-118120","P13.118121-118240","P13.118241-118400","P13.118401-118560"] as const);
export function integratedIntegrityAuditTerminalClosureDCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureDNode(input:Omit<IntegratedIntegrityAuditTerminalClosureDNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureDNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure D checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure D identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure D continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureDNode(node:IntegratedIntegrityAuditTerminalClosureDNode):IntegratedIntegrityAuditTerminalClosureDDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure D node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureDNode(node:IntegratedIntegrityAuditTerminalClosureDNode):Readonly<IntegratedIntegrityAuditTerminalClosureDNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureDDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureDNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure D replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureDReplayRegistry():void{registry.clear();}
