export type TerminalEvidenceIntegrityAuditDDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceIntegrityAuditDNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"AUDITED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.62241-62400","P13.62401-62520","P13.62521-62640","P13.62641-62800","P13.62801-62920","P13.62921-63040","P13.63041-63200","P13.63201-63320","P13.63321-63440","P13.63441-63600","P13.63601-63720","P13.63721-63840","P13.63841-64000","P13.64001-64120","P13.64121-64240","P13.64241-64400","P13.64401-64520","P13.64521-64640","P13.64641-64800","P13.64801-64920"] as const);
export function terminalEvidenceIntegrityAuditDCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceIntegrityAuditDNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string}):TerminalEvidenceIntegrityAuditDNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence integrity audit D checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence integrity audit D identity is incomplete.");return Object.freeze({...input,state:"AUDITED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceIntegrityAuditDNode(node:TerminalEvidenceIntegrityAuditDNode):TerminalEvidenceIntegrityAuditDDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence integrity audit D node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceIntegrityAuditDNode(node:TerminalEvidenceIntegrityAuditDNode):Readonly<TerminalEvidenceIntegrityAuditDNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceIntegrityAuditDDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceIntegrityAuditDNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence integrity audit D replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceIntegrityAuditDReplayRegistry():void{registry.clear();}
