export type IntegratedIntegrityAuditContinuityDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditContinuityNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;certificationArtifactId:string;certificationDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"CONTINUITY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.80921-81080","P13.81081-81200","P13.81201-81320","P13.81321-81480","P13.81481-81600","P13.81601-81720","P13.81721-81840","P13.81841-82000","P13.82001-82120","P13.82121-82240","P13.82241-82400","P13.82401-82520","P13.82521-82640","P13.82641-82800","P13.82801-82920","P13.82921-83040","P13.83041-83200","P13.83201-83320","P13.83321-83440","P13.83441-83600"] as const);
export function integratedIntegrityAuditContinuityCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditContinuityNode(input:Omit<IntegratedIntegrityAuditContinuityNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditContinuityNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit continuity checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.certificationArtifactId,input.certificationDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit continuity identity is incomplete.");if(input.certificationArtifactId!==input.parentArtifactId)throw new Error("Certification artifact continuity mismatch.");if(input.certificationDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit continuity fingerprint mismatch.");return Object.freeze({...input,state:"CONTINUITY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditContinuityNode(node:IntegratedIntegrityAuditContinuityNode):IntegratedIntegrityAuditContinuityDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit continuity node is executable or invalid.");if(node.certificationArtifactId!==node.parentArtifactId)throw new Error("Integrated integrity-audit continuity is invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.certificationArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditContinuityNode(node:IntegratedIntegrityAuditContinuityNode):Readonly<IntegratedIntegrityAuditContinuityNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditContinuityDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditContinuityNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit continuity replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditContinuityReplayRegistry():void{registry.clear();}
