export type IntegratedIntegrityAuditTerminalClosureBoundaryCDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureBoundaryCNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_BOUNDARY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.126721-126880","P13.126881-127000","P13.127001-127120","P13.127121-127280","P13.127281-127400","P13.127401-127520","P13.127521-127680","P13.127681-127800","P13.127801-127920","P13.127921-128080","P13.128081-128200","P13.128201-128320","P13.128321-128480","P13.128481-128600","P13.128601-128720","P13.128721-128880","P13.128881-129000","P13.129001-129120","P13.129121-129280","P13.129281-129440"] as const);
export function integratedIntegrityAuditTerminalClosureBoundaryCCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureBoundaryCNode(input:Omit<IntegratedIntegrityAuditTerminalClosureBoundaryCNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureBoundaryCNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure boundary C checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure boundary C identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure boundary C continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_BOUNDARY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureBoundaryCNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryCNode):IntegratedIntegrityAuditTerminalClosureBoundaryCDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure boundary C node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureBoundaryCNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryCNode):Readonly<IntegratedIntegrityAuditTerminalClosureBoundaryCNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureBoundaryCDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureBoundaryCNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure boundary C replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureBoundaryCReplayRegistry():void{registry.clear();}
