export type IntegratedIntegrityAuditTerminalClosureEDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureENode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.118561-118720","P13.118721-118840","P13.118841-118960","P13.118961-119120","P13.119121-119240","P13.119241-119360","P13.119361-119520","P13.119521-119640","P13.119641-119760","P13.119761-119920","P13.119921-120040","P13.120041-120160","P13.120161-120320","P13.120321-120440","P13.120441-120560","P13.120561-120720","P13.120721-120840","P13.120841-120960","P13.120961-121120","P13.121121-121280"] as const);
export function integratedIntegrityAuditTerminalClosureECheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureENode(input:Omit<IntegratedIntegrityAuditTerminalClosureENode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureENode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure E checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure E identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure E continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureENode(node:IntegratedIntegrityAuditTerminalClosureENode):IntegratedIntegrityAuditTerminalClosureEDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure E node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureENode(node:IntegratedIntegrityAuditTerminalClosureENode):Readonly<IntegratedIntegrityAuditTerminalClosureENode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureEDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureENode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure E replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureEReplayRegistry():void{registry.clear();}
