export type TerminalEvidenceContinuationFDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceContinuationFNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.40881-41040","P13.41041-41160","P13.41161-41280","P13.41281-41440","P13.41441-41560","P13.41561-41680","P13.41681-41840","P13.41841-41960","P13.41961-42080","P13.42081-42240","P13.42241-42360","P13.42361-42480","P13.42481-42640","P13.42641-42760","P13.42761-42880","P13.42881-43040","P13.43041-43160","P13.43161-43280","P13.43281-43440","P13.43441-43560"] as const);
export function terminalEvidenceContinuationFCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationFNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationFNode["state"]}):TerminalEvidenceContinuationFNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation F checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation F identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationFNode(node:TerminalEvidenceContinuationFNode):TerminalEvidenceContinuationFDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation F node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationFNode(node:TerminalEvidenceContinuationFNode):Readonly<TerminalEvidenceContinuationFNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationFDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationFNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation F replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationFReplayRegistry():void{registry.clear();}
