export type IntegratedIntegrityAuditContinuityDDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditContinuityDNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;certificationArtifactId:string;certificationDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"CONTINUITY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.88921-89080","P13.89081-89200","P13.89201-89320","P13.89321-89480","P13.89481-89600","P13.89601-89720","P13.89721-89840","P13.89841-90000","P13.90001-90120","P13.90121-90240","P13.90241-90400","P13.90401-90520","P13.90521-90640","P13.90641-90800","P13.90801-90920","P13.90921-91040","P13.91041-91200","P13.91201-91320","P13.91321-91440","P13.91441-91600"] as const);
export function integratedIntegrityAuditContinuityDCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditContinuityDNode(input:Omit<IntegratedIntegrityAuditContinuityDNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditContinuityDNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit continuity D checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.certificationArtifactId,input.certificationDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit continuity D identity is incomplete.");if(input.certificationArtifactId!==input.parentArtifactId||input.auditDecisionFingerprint!==input.decisionFingerprint||input.certificationDecisionFingerprint===input.decisionFingerprint)throw new Error("Integrated integrity-audit continuity D chain mismatch.");return Object.freeze({...input,state:"CONTINUITY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditContinuityDNode(node:IntegratedIntegrityAuditContinuityDNode):IntegratedIntegrityAuditContinuityDDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit continuity D node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.certificationArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditContinuityDNode(node:IntegratedIntegrityAuditContinuityDNode):Readonly<IntegratedIntegrityAuditContinuityDNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditContinuityDDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditContinuityDNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit continuity D replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditContinuityDReplayRegistry():void{registry.clear();}
