export type TerminalEvidenceIntegrityAuditBDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceIntegrityAuditBNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"AUDITED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.56961-57080","P13.57081-57200","P13.57201-57320","P13.57321-57480","P13.57481-57600","P13.57601-57720","P13.57721-57880","P13.57881-58000","P13.58001-58120","P13.58121-58280","P13.58281-58400","P13.58401-58520","P13.58521-58680","P13.58681-58800","P13.58801-58920","P13.58921-59080","P13.59081-59200","P13.59201-59320","P13.59321-59480","P13.59481-59520"] as const);
export function terminalEvidenceIntegrityAuditBCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceIntegrityAuditBNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string}):TerminalEvidenceIntegrityAuditBNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence integrity audit B checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence integrity audit B identity is incomplete.");return Object.freeze({...input,state:"AUDITED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceIntegrityAuditBNode(node:TerminalEvidenceIntegrityAuditBNode):TerminalEvidenceIntegrityAuditBDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence integrity audit B node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceIntegrityAuditBNode(node:TerminalEvidenceIntegrityAuditBNode):Readonly<TerminalEvidenceIntegrityAuditBNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceIntegrityAuditBDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceIntegrityAuditBNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence integrity audit B replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceIntegrityAuditBReplayRegistry():void{registry.clear();}
