export type TerminalEvidenceIntegrityAuditCDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceIntegrityAuditCNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"AUDITED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.59521-59680","P13.59681-59800","P13.59801-59920","P13.59921-60080","P13.60081-60200","P13.60201-60320","P13.60321-60480","P13.60481-60600","P13.60601-60720","P13.60721-60880","P13.60881-61000","P13.61001-61120","P13.61121-61280","P13.61281-61400","P13.61401-61520","P13.61521-61680","P13.61681-61800","P13.61801-61920","P13.61921-62080","P13.62081-62240"] as const);
export function terminalEvidenceIntegrityAuditCCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceIntegrityAuditCNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string}):TerminalEvidenceIntegrityAuditCNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence integrity audit C checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence integrity audit C identity is incomplete.");return Object.freeze({...input,state:"AUDITED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceIntegrityAuditCNode(node:TerminalEvidenceIntegrityAuditCNode):TerminalEvidenceIntegrityAuditCDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence integrity audit C node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceIntegrityAuditCNode(node:TerminalEvidenceIntegrityAuditCNode):Readonly<TerminalEvidenceIntegrityAuditCNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceIntegrityAuditCDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceIntegrityAuditCNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence integrity audit C replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceIntegrityAuditCReplayRegistry():void{registry.clear();}
