export type IntegratedIntegrityAuditContinuityBDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditContinuityBNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;certificationArtifactId:string;certificationDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"CONTINUITY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.83601-83720","P13.83721-83840","P13.83841-84000","P13.84001-84120","P13.84121-84240","P13.84241-84400","P13.84401-84520","P13.84521-84640","P13.84641-84800","P13.84801-84920","P13.84921-85040","P13.85041-85200","P13.85201-85320","P13.85321-85440","P13.85441-85600","P13.85601-85720","P13.85721-85840","P13.85841-86000","P13.86001-86120","P13.86121-86240"] as const);
export function integratedIntegrityAuditContinuityBCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditContinuityBNode(input:Omit<IntegratedIntegrityAuditContinuityBNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditContinuityBNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit continuity B checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.certificationArtifactId,input.certificationDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit continuity B identity is incomplete.");if(input.certificationArtifactId!==input.parentArtifactId)throw new Error("Certification artifact continuity mismatch.");if(input.certificationDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit continuity B fingerprint mismatch.");return Object.freeze({...input,state:"CONTINUITY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditContinuityBNode(node:IntegratedIntegrityAuditContinuityBNode):IntegratedIntegrityAuditContinuityBDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit continuity B node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.certificationArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditContinuityBNode(node:IntegratedIntegrityAuditContinuityBNode):Readonly<IntegratedIntegrityAuditContinuityBNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditContinuityBDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditContinuityBNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit continuity B replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditContinuityBReplayRegistry():void{registry.clear();}
