export type IntegratedIntegrityAuditTerminalClosureDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.107681-107840","P13.107841-107960","P13.107961-108080","P13.108081-108240","P13.108241-108360","P13.108361-108480","P13.108481-108640","P13.108641-108760","P13.108761-108880","P13.108881-109040","P13.109041-109160","P13.109161-109280","P13.109281-109440","P13.109441-109560","P13.109561-109680","P13.109681-109840","P13.109841-109960","P13.109961-110120","P13.110121-110240","P13.110241-110400"] as const);
export function integratedIntegrityAuditTerminalClosureCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureNode(input:Omit<IntegratedIntegrityAuditTerminalClosureNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureNode(node:IntegratedIntegrityAuditTerminalClosureNode):IntegratedIntegrityAuditTerminalClosureDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure node is executable or invalid.");if(node.closureArtifactId!==node.parentArtifactId)throw new Error("Integrated integrity-audit terminal-closure chain is invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureNode(node:IntegratedIntegrityAuditTerminalClosureNode):Readonly<IntegratedIntegrityAuditTerminalClosureNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureReplayRegistry():void{registry.clear();}
