export type TerminalEvidenceContinuationIDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceContinuationINode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.48921-49080","P13.49081-49200","P13.49201-49320","P13.49321-49480","P13.49481-49600","P13.49601-49720","P13.49721-49880","P13.49881-50000","P13.50001-50120","P13.50121-50280","P13.50281-50400","P13.50401-50520","P13.50521-50680","P13.50681-50800","P13.50801-50920","P13.50921-51080","P13.51081-51200","P13.51201-51320","P13.51321-51480","P13.51481-51600"] as const);
export function terminalEvidenceContinuationICheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationINode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationINode["state"]}):TerminalEvidenceContinuationINode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation I checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation I identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationINode(node:TerminalEvidenceContinuationINode):TerminalEvidenceContinuationIDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation I node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationINode(node:TerminalEvidenceContinuationINode):Readonly<TerminalEvidenceContinuationINode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationIDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationINode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation I replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationIReplayRegistry():void{registry.clear();}
