export type TerminalEvidenceContinuationDDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceContinuationDNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.35561-35680","P13.35681-35840","P13.35841-35960","P13.35961-36080","P13.36081-36240","P13.36241-36360","P13.36361-36480","P13.36481-36640","P13.36641-36760","P13.36761-36880","P13.36881-37040","P13.37041-37160","P13.37161-37280","P13.37281-37440","P13.37441-37560","P13.37561-37680","P13.37681-37840","P13.37841-37960","P13.37961-38080","P13.38081-38240"] as const);
export function terminalEvidenceContinuationDCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationDNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationDNode["state"]}):TerminalEvidenceContinuationDNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation D checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation D identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationDNode(node:TerminalEvidenceContinuationDNode):TerminalEvidenceContinuationDDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation D node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationDNode(node:TerminalEvidenceContinuationDNode):Readonly<TerminalEvidenceContinuationDNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationDDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationDNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation D replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationDReplayRegistry():void{registry.clear();}
