export type IntegratedIntegrityAuditContinuityEDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditContinuityENode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;certificationArtifactId:string;certificationDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"CONTINUITY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.91601-91720","P13.91721-91840","P13.91841-92000","P13.92001-92120","P13.92121-92240","P13.92241-92400","P13.92401-92520","P13.92521-92640","P13.92641-92800","P13.92801-92920","P13.92921-93040","P13.93041-93200","P13.93201-93320","P13.93321-93440","P13.93441-93600","P13.93601-93720","P13.93721-93840","P13.93841-94000","P13.94001-94120","P13.94121-94280"] as const);
export function integratedIntegrityAuditContinuityECheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditContinuityENode(input:Omit<IntegratedIntegrityAuditContinuityENode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditContinuityENode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit continuity E checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.certificationArtifactId,input.certificationDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit continuity E identity is incomplete.");if(input.certificationArtifactId!==input.parentArtifactId||input.auditDecisionFingerprint!==input.decisionFingerprint||input.certificationDecisionFingerprint===input.decisionFingerprint)throw new Error("Integrated integrity-audit continuity E chain mismatch.");return Object.freeze({...input,state:"CONTINUITY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditContinuityENode(node:IntegratedIntegrityAuditContinuityENode):IntegratedIntegrityAuditContinuityEDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit continuity E node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.certificationArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditContinuityENode(node:IntegratedIntegrityAuditContinuityENode):Readonly<IntegratedIntegrityAuditContinuityENode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditContinuityEDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditContinuityENode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit continuity E replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditContinuityEReplayRegistry():void{registry.clear();}
