export type TerminalEvidenceContinuationGDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type TerminalEvidenceContinuationGNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.43561-43720","P13.43721-43840","P13.43841-43960","P13.43961-44120","P13.44121-44240","P13.44241-44360","P13.44361-44520","P13.44521-44640","P13.44641-44760","P13.44761-44920","P13.44921-45040","P13.45041-45160","P13.45161-45320","P13.45321-45440","P13.45441-45560","P13.45561-45720","P13.45721-45840","P13.45841-45960","P13.45961-46120","P13.46121-46240"] as const);
export function terminalEvidenceContinuationGCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationGNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationGNode["state"]}):TerminalEvidenceContinuationGNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation G checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation G identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationGNode(node:TerminalEvidenceContinuationGNode):TerminalEvidenceContinuationGDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation G node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationGNode(node:TerminalEvidenceContinuationGNode):Readonly<TerminalEvidenceContinuationGNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationGDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationGNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation G replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationGReplayRegistry():void{registry.clear();}
