export type TerminalEvidenceContinuationBDisposition = "ADMIT" | "REPLAY" | "CONFLICT";
export type TerminalEvidenceContinuationBNode = Readonly<{ checkpoint:string; artifactId:string; parentArtifactId:string; decisionFingerprint:string; state:"CLOSED_FOR_REVIEW"|"VERIFIED_FOR_REVIEW"|"READY_FOR_REVIEW"; authorizationGranted:false; dispatchApproved:false; externalTransportRequested:false; dispatchExecuted:false; durablePublicationCreated:false; syntheticOnly:true }>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.30241-30360","P13.30361-30480","P13.30481-30640","P13.30641-30760","P13.30761-30880","P13.30881-31040","P13.31041-31160","P13.31161-31280","P13.31281-31440","P13.31441-31560","P13.31561-31680","P13.31681-31840","P13.31841-31960","P13.31961-32080","P13.32081-32240","P13.32241-32360","P13.32361-32480","P13.32481-32640","P13.32641-32760","P13.32761-32880"] as const);
export function terminalEvidenceContinuationBCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createTerminalEvidenceContinuationBNode(input:{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;state:TerminalEvidenceContinuationBNode["state"]}):TerminalEvidenceContinuationBNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported terminal evidence continuation B checkpoint.");if(!input.artifactId.trim()||!input.parentArtifactId.trim()||!input.decisionFingerprint.trim())throw new Error("Terminal evidence continuation B identity is incomplete.");return Object.freeze({...input,authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayTerminalEvidenceContinuationBNode(node:TerminalEvidenceContinuationBNode):TerminalEvidenceContinuationBDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Terminal evidence continuation B node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}`;const previous=registry.get(key);if(previous===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return previous===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyTerminalEvidenceContinuationBNode(node:TerminalEvidenceContinuationBNode):Readonly<TerminalEvidenceContinuationBNode&{certified:true;replayDisposition:Exclude<TerminalEvidenceContinuationBDisposition,"CONFLICT">}>{const replayDisposition=replayTerminalEvidenceContinuationBNode(node);if(replayDisposition==="CONFLICT")throw new Error("Terminal evidence continuation B replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetTerminalEvidenceContinuationBReplayRegistry():void{registry.clear();}
