export type IntegratedIntegrityAuditContinuityCDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditContinuityCNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;certificationArtifactId:string;certificationDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"CONTINUITY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.86241-86360","P13.86361-86480","P13.86481-86600","P13.86601-86720","P13.86721-86840","P13.86841-87000","P13.87001-87120","P13.87121-87240","P13.87241-87400","P13.87401-87520","P13.87521-87640","P13.87641-87800","P13.87801-87920","P13.87921-88040","P13.88041-88200","P13.88201-88320","P13.88321-88440","P13.88441-88600","P13.88601-88720","P13.88721-88920"] as const);
export function integratedIntegrityAuditContinuityCCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditContinuityCNode(input:Omit<IntegratedIntegrityAuditContinuityCNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditContinuityCNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit continuity C checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.certificationArtifactId,input.certificationDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit continuity C identity is incomplete.");if(input.certificationArtifactId!==input.parentArtifactId||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit continuity C chain mismatch.");if(input.certificationDecisionFingerprint===input.decisionFingerprint)throw new Error("Integrated continuity requires a distinct certification fingerprint.");return Object.freeze({...input,state:"CONTINUITY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditContinuityCNode(node:IntegratedIntegrityAuditContinuityCNode):IntegratedIntegrityAuditContinuityCDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit continuity C node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.certificationArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditContinuityCNode(node:IntegratedIntegrityAuditContinuityCNode):Readonly<IntegratedIntegrityAuditContinuityCNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditContinuityCDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditContinuityCNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit continuity C replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditContinuityCReplayRegistry():void{registry.clear();}
