export type IntegratedIntegrityAuditTerminalClosureBoundaryDisposition="ADMIT"|"REPLAY"|"CONFLICT";
export type IntegratedIntegrityAuditTerminalClosureBoundaryNode=Readonly<{checkpoint:string;artifactId:string;parentArtifactId:string;decisionFingerprint:string;closureArtifactId:string;closureDecisionFingerprint:string;auditArtifactId:string;auditDecisionFingerprint:string;state:"TERMINAL_CLOSURE_BOUNDARY_VERIFIED_FOR_REVIEW";authorizationGranted:false;dispatchApproved:false;externalTransportRequested:false;dispatchExecuted:false;durablePublicationCreated:false;syntheticOnly:true}>;
const registry=new Map<string,string>();
const CHECKPOINTS=Object.freeze(["P13.121281-121440","P13.121441-121560","P13.121561-121680","P13.121681-121840","P13.121841-121960","P13.121961-122080","P13.122081-122240","P13.122241-122360","P13.122361-122480","P13.122481-122640","P13.122641-122760","P13.122761-122880","P13.122881-123040","P13.123041-123160","P13.123161-123280","P13.123281-123440","P13.123441-123560","P13.123561-123680","P13.123681-123840","P13.123841-124000"] as const);
export function integratedIntegrityAuditTerminalClosureBoundaryCheckpoints():readonly string[]{return CHECKPOINTS;}
export function createIntegratedIntegrityAuditTerminalClosureBoundaryNode(input:Omit<IntegratedIntegrityAuditTerminalClosureBoundaryNode,"state"|"authorizationGranted"|"dispatchApproved"|"externalTransportRequested"|"dispatchExecuted"|"durablePublicationCreated"|"syntheticOnly">):IntegratedIntegrityAuditTerminalClosureBoundaryNode{if(!(CHECKPOINTS as readonly string[]).includes(input.checkpoint))throw new Error("Unsupported integrated integrity-audit terminal-closure boundary checkpoint.");for(const v of [input.artifactId,input.parentArtifactId,input.decisionFingerprint,input.closureArtifactId,input.closureDecisionFingerprint,input.auditArtifactId,input.auditDecisionFingerprint])if(!v.trim())throw new Error("Integrated integrity-audit terminal-closure boundary identity is incomplete.");if(input.closureArtifactId!==input.parentArtifactId||input.closureDecisionFingerprint===input.decisionFingerprint||input.auditDecisionFingerprint!==input.decisionFingerprint)throw new Error("Integrated integrity-audit terminal-closure boundary continuity mismatch.");return Object.freeze({...input,state:"TERMINAL_CLOSURE_BOUNDARY_VERIFIED_FOR_REVIEW",authorizationGranted:false,dispatchApproved:false,externalTransportRequested:false,dispatchExecuted:false,durablePublicationCreated:false,syntheticOnly:true});}
export function replayIntegratedIntegrityAuditTerminalClosureBoundaryNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryNode):IntegratedIntegrityAuditTerminalClosureBoundaryDisposition{if(!node.syntheticOnly||node.authorizationGranted||node.dispatchApproved||node.externalTransportRequested||node.dispatchExecuted||node.durablePublicationCreated)throw new Error("Integrated integrity-audit terminal-closure boundary node is executable or invalid.");const key=`${node.checkpoint}:${node.artifactId}:${node.parentArtifactId}:${node.closureArtifactId}:${node.auditArtifactId}`;const p=registry.get(key);if(p===undefined){registry.set(key,node.decisionFingerprint);return "ADMIT";}return p===node.decisionFingerprint?"REPLAY":"CONFLICT";}
export function certifyIntegratedIntegrityAuditTerminalClosureBoundaryNode(node:IntegratedIntegrityAuditTerminalClosureBoundaryNode):Readonly<IntegratedIntegrityAuditTerminalClosureBoundaryNode&{certified:true;replayDisposition:Exclude<IntegratedIntegrityAuditTerminalClosureBoundaryDisposition,"CONFLICT">}>{const replayDisposition=replayIntegratedIntegrityAuditTerminalClosureBoundaryNode(node);if(replayDisposition==="CONFLICT")throw new Error("Integrated integrity-audit terminal-closure boundary replay conflict.");return Object.freeze({...node,certified:true,replayDisposition});}
export function resetIntegratedIntegrityAuditTerminalClosureBoundaryReplayRegistry():void{registry.clear();}
