(()=>{
'use strict';
const K='mta-deteni-demo-v2';
const get=()=>window.MTADeteniStateKernel?window.MTADeteniStateKernel.read():(()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return {}}})();
const put=d=>{const kernel=window.MTADeteniStateKernel;if(!kernel)throw new Error('CANONICAL_STATE_KERNEL_REQUIRED');return kernel.write(d)};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const audit=(action,type,id,result='SUCCESS')=>{const d=get(),kernel=window.MTADeteniStateKernel;if(!kernel)throw new Error('CANONICAL_AUDIT_KERNEL_REQUIRED');kernel.audit(d,action,type,id,result,{actor:'DEMO-OPERATOR'});return put(d)};
function ensure(){const source=get(),d=structuredClone(source);d.qr=d.qr&&typeof d.qr==='object'?d.qr:{detainee:{},room:{},leave:{}};d.qr.detainee=d.qr.detainee||{};d.qr.room=d.qr.room||{};d.qr.leave=d.qr.leave||{};d.rooms=Array.isArray(d.rooms)?d.rooms:[{id:'ROOM-A01',block:'Blok A',room:'Kamar 01',capacity:8,status:'ACTIVE'},{id:'ROOM-A02',block:'Blok A',room:'Kamar 02',capacity:8,status:'ACTIVE'},{id:'ROOM-B01',block:'Blok B',room:'Kamar 01',capacity:8,status:'ACTIVE'},{id:'ROOM-B02',block:'Blok B',room:'Kamar 02',capacity:8,status:'ACTIVE'}];(d.detainees||[]).forEach(x=>{if(x?.id&&!d.qr.detainee[x.id])d.qr.detainee[x.id]={token:'SYNTH-QR-'+x.id,status:x.status==='AKTIF'?'ACTIVE':'SUSPENDED',context:'DETAINEE',issuedAt:x.createdAt||new Date().toISOString()}});d.rooms.forEach(x=>{if(!d.qr.room[x.id])d.qr.room[x.id]={token:'SYNTH-QR-'+x.id,status:x.status==='ACTIVE'?'ACTIVE':'SUSPENDED'}});return d}
function boot(){if(document.querySelector('#mtaPreviewV5'))return;const s=document.createElement('style');s.id='mtaPreviewV5';s.textContent='.p5g{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:12px}.p5c{background:#fff;border:1px solid var(--line);border-radius:13px;padding:14px}.p5tag{display:inline-block;padding:4px 8px;border-radius:99px;background:#eef4ff;color:#245ca8;font-size:10px}.p5row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.p5in{padding:10px;border:1px solid var(--line);border-radius:9px;width:100%}.p5qr{min-width:210px;min-height:210px;display:grid;place-items:center;background:#fff;border:1px solid var(--line);border-radius:12px}.p5mini{font-size:11px;color:var(--muted)}@media(max-width:900px){.p5g{grid-template-columns:1fr 1fr}}@media(max-width:600px){.p5g{grid-template-columns:1fr}}';document.head.appendChild(s);window.MTAPreviewV5Views=Object.freeze({render})}
function render(v){const r=document.querySelector('#appView');if(!r)return;const d=ensure();if(v==='p5monitor')monitor(r,d);if(v==='p5qr')qr(r,d);if(v==='p5scan')scan(r,d);if(v==='p5ops')ops(r,d)}
function monitor(r,d){const a=(d.detainees||[]).filter(x=>x.status==='AKTIF').length;r.innerHTML='<section class="hero"><h1>Operational Monitor</h1><p class="sub">Surface pengujian alur operasional menggunakan data sintetis.</p></section><div class="p5g"><div class="p5c"><b>'+a+'</b><div class="p5mini">Deteni aktif</div></div><div class="p5c"><b>'+d.rooms.length+'</b><div class="p5mini">Kamar terdaftar</div></div><div class="p5c"><b>'+(d.audit||[]).length+'</b><div class="p5mini">Audit events</div></div></div>'}
function qr(r,d){const ds=d.detainees.map(x=>'<tr><td>'+E(x.code)+'</td><td>'+E(x.name)+'</td><td>'+E(d.qr.detainee[x.id]?.token||'')+'</td><td><button class="btn small" onclick="window.p5showQR(\'detainee\',\''+E(x.id)+'\')">QR</button> <button class="btn small" onclick="window.p5printDetaineeQR(\''+E(x.id)+'\')">Cetak</button></td></tr>').join('');const rs=d.rooms.map(x=>'<tr><td>'+E(x.block)+'</td><td>'+E(x.room)+'</td><td>'+E(d.qr.room[x.id]?.token||'')+'</td><td><button class="btn small" onclick="window.p5showQR(\'room\',\''+E(x.id)+'\')">QR</button></td></tr>').join('');r.innerHTML='<section class="hero"><h1>QR Center</h1><p class="sub">QR resource center.</p></section><div class="p5g"><div class="p5c"><h2>QR Individu</h2><table class="table"><tbody>'+ds+'</tbody></table></div><div class="p5c"><h2>QR Kamar</h2><table class="table"><tbody>'+rs+'</tbody></table></div></div>'}
window.p5printDetaineeQR=id=>window.p6printQR?window.p6printQR('detainee',id):toast('Mesin cetak QR belum siap');
window.p5downloadDetaineeQR=id=>{const d=ensure(),q=d.qr.detainee[id],x=d.detainees.find(z=>z.id===id);if(!q||!x||!window.qrcode)return toast('QR deteni belum tersedia');const payload='mta://detainee/'+id+'/'+q.token,g=qrcode(0,'M');g.addData(payload);g.make();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([g.createSvgTag(8,0)],{type:'image/svg+xml'}));a.download='QR-'+x.code+'.svg';document.body.appendChild(a);a.click();a.remove();audit('QR_DOWNLOAD','QR',id)};
window.p5showQR=(kind,id)=>{const d=ensure(),map=kind==='room'?'room':'detainee',q=d.qr[map]?.[id],x=kind==='room'?d.rooms.find(z=>z.id===id):d.detainees.find(z=>z.id===id);if(!q||!x)return;const payload=`mta://${kind}/${id}/${q.token}`;openModal('<div class="dialoghead"><h2>QR</h2><button class="x" onclick="closeModal()">×</button></div><div class="p5row"><div id="p5qrbox" class="p5qr"></div><div><h3>'+E(kind==='room'?x.block+' / '+x.room:x.code+' · '+x.name)+'</h3><button class="btn primary" onclick="window.p6printQR(\''+E(kind)+'\',\''+E(id)+'\')">Cetak / PDF</button></div></div>');setTimeout(()=>{if(window.qrcode){const g=qrcode(0,'M');g.addData(payload);g.make();document.querySelector('#p5qrbox').innerHTML=g.createSvgTag(6,0)}},50);audit('QR_VIEW','QR',id)};
function scan(r,d){r.innerHTML='<section class="hero"><h1>Scan Center</h1><p class="sub">Functional journey: Scan → Resolve → Data → Action → Audit.</p></section><div class="p5c"><div class="p5row"><input id="p5scanin" class="p5in" placeholder="mta://detainee/id/token"><button class="btn primary" onclick="window.p5resolve()">Resolve</button></div><div id="p5out" style="margin-top:12px"></div></div>'}
window.p5openDetainee=id=>{const d=ensure(),x=d.detainees.find(z=>z.id===id);if(!x)return toast('Deteni tidak ditemukan.');audit('SCAN_ACTION_OPEN_DETAINEE','DETAINEE',id);if(window.MTADetaineeDetailView?.detail)return window.MTADetaineeDetailView.detail(id);show('detainee-detail')};
window.p5openMovement=id=>{audit('SCAN_ACTION_MOVEMENT','DETAINEE',id);show('movement');setTimeout(()=>{const select=document.querySelector('#p9moveForm select[name="detaineeId"]');if(select){select.value=id;select.dispatchEvent(new Event('change',{bubbles:true}))}},0)};
window.p5resolve=()=>{const raw=(document.querySelector('#p5scanin')?.value||'').trim();if(typeof window.mtaUnifiedResolve==='function')return window.mtaUnifiedResolve(raw);const d=ensure();let type='',hit=null;if(raw.startsWith('mta://detainee/')){type='DETAINEE';const parts=raw.split('/').filter(Boolean);const token=parts[parts.length-1];const resourceId=parts.length>=4?parts[parts.length-2]:'';hit=resourceId&&d.qr.detainee[resourceId]?[resourceId,d.qr.detainee[resourceId]]:Object.entries(d.qr.detainee).find(([,q])=>q.token===token)}else if(raw.startsWith('mta://room/')){type='ROOM';const parts=raw.split('/').filter(Boolean);const token=parts[parts.length-1];const resourceId=parts.length>=4?parts[parts.length-2]:'';hit=resourceId&&d.qr.room[resourceId]?[resourceId,d.qr.room[resourceId]]:Object.entries(d.qr.room).find(([,q])=>q.token===token)}else if(raw.startsWith('mta://leave/')){type='LEAVE';const token=raw.split('/').pop();hit=Object.entries(d.qr.leave).find(([,q])=>q.token===token)}const out=document.querySelector('#p5out');if(!hit){out.innerHTML='<div class="notice">Resolution DENIED · token tidak ditemukan atau tidak valid.</div>';audit('SCAN_RESOLVE','QR_SCAN',raw,'FAILED');return}const id=hit[0];out.innerHTML='<div class="notice"><b>'+type+'</b> · '+E(hit[1].status)+'<br>Resource: '+E(id)+'<div class="p5row"><button class="btn primary" onclick="window.p5openDetainee(\''+E(id)+'\')">Data Deteni</button><button class="btn" onclick="window.p5openMovement(\''+E(id)+'\')">Pergerakan</button></div></div>';audit('SCAN_RESOLVE','QR_SCAN',id)};
function ops(r,d){const q=(d.leaves||[]).filter(x=>x.status!=='COMPLETED');r.innerHTML='<section class="hero"><h1>Operational Queue</h1><p class="sub">Antrian tindakan berbasis state sintetis.</p></section><div class="p5g"><div class="p5c"><h2>Leave queue</h2><b>'+q.length+'</b></div><div class="p5c"><h2>Governance</h2><span class="p5tag">SYNTHETIC ONLY</span> <span class="p5tag">AI OFF</span></div></div>'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();