(()=>{
const K='mta-deteni-demo-v2';const get=()=>JSON.parse(localStorage.getItem(K)||'{}');const put=d=>localStorage.setItem(K,JSON.stringify(d));const E=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));const uid=p=>p+'-'+crypto.randomUUID().slice(0,10).toUpperCase();const audit=(a,t,i,r='SUCCESS')=>{const d=get();d.audit=d.audit||[];d.audit.unshift({id:uid('AUD'),action:a,resourceType:t,resourceId:i||'',result:r,occurredAt:new Date().toISOString(),actor:'DEMO-OPERATOR',requestId:uid('REQ'),correlationId:uid('COR'),policyVersion:'AUTHZ-1.0'});put(d)};
function ensure(){const d=get();d.qr=d.qr||{detainee:{},room:{},leave:{}};d.rooms=d.rooms||[];d.leaves=d.leaves||[];d.rooms.forEach(x=>d.qr.room[x.id]=d.qr.room[x.id]||{token:uid('RMQR'),status:x.status||'ACTIVE'});d.leaves.forEach(x=>{if(['APPROVED','DEPARTED','RETURNED'].includes(x.status)&&!d.qr.leave[x.id])d.qr.leave[x.id]={token:uid('LVQR'),status:'ACTIVE'}});put(d);return d}
function boot(){if(document.querySelector('#mtaPreviewV6'))return;const s=document.createElement('style');s.id='mtaPreviewV6';s.textContent='.p6grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:12px}.p6card{background:#fff;border:1px solid var(--line);border-radius:13px;padding:14px}.p6tag{display:inline-block;padding:4px 8px;border-radius:99px;background:#eef4ff;color:#245ca8;font-size:10px}.p6row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.p6input{width:100%;padding:10px;border:1px solid var(--line);border-radius:9px}.p6video{width:100%;max-width:520px;border-radius:14px;background:#111;min-height:260px}.p6danger{color:#b42318}.p6ok{color:#16763b}.p6print{display:none}@media(max-width:900px){.p6grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.p6grid{grid-template-columns:1fr}}';document.head.appendChild(s);const nav=document.querySelector('#nav');[['p6r','Room Ops','p6rooms'],['p6l','Leave QR','p6leaveqr'],['p6c','Camera Scan','p6camera'],['p6d','Reports','p6reports']].forEach(([id,label,v])=>{const b=document.createElement('button');b.id=id; b.dataset.view=v;b.textContent=label;nav.appendChild(b);b.onclick=()=>window.show(v)});const old=window.show;window.show=v=>['p6rooms','p6leaveqr','p6camera','p6reports'].includes(v)?render(v):old(v);ensure()}
function render(v){const r=document.querySelector('#appView');const d=ensure();if(v==='p6rooms')rooms(r,d);if(v==='p6leaveqr')leaveqr(r,d);if(v==='p6camera')camera(r,d);if(v==='p6reports')reports(r,d)}
function rooms(r,d){const rows=d.rooms.map(x=>{const occ=d.placements.filter(p=>p.block===x.block&&p.room===x.room).length;const q=d.qr.room[x.id];return `<tr><td>${E(x.block)}</td><td>${E(x.room)}</td><td>${occ}/${x.capacity}</td><td><span class="p6tag">${E(q.status)}</span></td><td>${E(q.token)}</td><td><button class="btn small" onclick="window.p6qr('room','${x.id}')">QR</button> <button class="btn small" onclick="window.p6roomState('${x.id}')">State</button></td></tr>`}).join('');r.innerHTML=`<section class="hero"><h1>Room Operations</h1><p class="sub">Kontrol lifecycle kamar dan QR permanen. Perubahan hanya simulasi lokal.</p></section><div class="p6card"><div class="tablewrap"><table class="table"><thead><tr><th>Blok</th><th>Kamar</th><th>Occupancy</th><th>QR State</th><th>Token</th><th>Aksi</th></tr></thead><tbody>${rows||'<tr><td colspan="6" class="empty">Belum ada kamar</td></tr>'}</tbody></table></div></div>`}
window.p6roomState=id=>{const d=ensure(),x=d.rooms.find(z=>z.id===id),q=d.qr.room[id];if(!x||!q)return;const next={ACTIVE:'SUSPENDED',SUSPENDED:'REVOKED',REVOKED:'ACTIVE'}[q.status]||'ACTIVE';q.status=next;x.status=next;put(d);audit('QR_ROOM_STATE_CHANGE','ROOM_QR',id);toast('Room QR state → '+next);render('p6rooms')};
function leaveqr(r,d){const rows=d.leaves.map(x=>{const q=d.qr.leave[x.id];return `<tr><td>${E(x.id)}</td><td>${E(x.status)}</td><td>${E(x.destination)}</td><td>${q?E(q.token):'—'}</td><td>${q?`<button class="btn small" onclick="window.p6qr('leave','${x.id}')">QR</button>`:['APPROVED','DEPARTED'].includes(x.status)?`<button class="btn small primary" onclick="window.p6issue('${x.id}')">Issue QR</button>`:'—'}</td></tr>`}).join('');r.innerHTML=`<section class="hero"><h1>Temporary Leave QR</h1><p class="sub">QR transaksi izin sementara, terpisah dari QR permanen kamar.</p></section><div class="p6card"><div class="tablewrap"><table class="table"><thead><tr><th>ID</th><th>Status</th><th>Tujuan</th><th>Token</th><th>Aksi</th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="empty">Belum ada transaksi izin</td></tr>'}</tbody></table></div></div>`}
window.p6issue=id=>{const d=ensure(),l=d.leaves.find(x=>x.id===id);if(!l||!['APPROVED','DEPARTED'].includes(l.status)){toast('Issue QR ditolak: state izin tidak memenuhi gate');audit('LEAVE_QR_ISSUE','LEAVE',id,'DENIED');return}d.qr.leave[id]={token:uid('LVQR'),status:'ACTIVE'};put(d);audit('LEAVE_QR_ISSUE','LEAVE_QR',id);toast('QR izin diterbitkan secara synthetic');render('p6leaveqr')};
window.p6qr=(kind,id)=>{const d=ensure(),map=kind==='room'?'room':kind==='leave'?'leave':'detainee',q=d.qr[map][id],x=kind==='room'?d.rooms.find(z=>z.id===id):kind==='leave'?d.leaves.find(z=>z.id===id):d.detainees.find(z=>z.id===id);if(!q||!x)return;const payload='mta://'+kind+'/'+id+'/'+q.token;const label=kind==='room'?x.block+' / '+x.room:kind==='leave'?x.id+' · '+x.destination:x.code+' · '+x.name;openModal(`<div class="dialoghead"><h2>QR ${kind.toUpperCase()}</h2><button class="x" onclick="closeModal()">×</button></div><div class="p6row"><div id="p6qrbox" class="p5qr"></div><div><h3>${E(label)}</h3><span class="p6tag">${E(q.status)}</span><p><code>${E(payload)}</code></p><button class="btn primary" onclick="window.p6printQR('${kind}','${id}')">Cetak QR</button></div></div><div class="notice">Opaque token · QR bukan autentikasi · resolusi tetap melewati policy boundary.</div>`);setTimeout(()=>{if(window.qrcode){const g=qrcode(0,'M');g.addData(payload);g.make();document.querySelector('#p6qrbox').innerHTML=g.createSvgTag(6,0)}},100);audit('QR_VIEW','QR',id)};
window.p6printQR=(kind,id)=>{const d=ensure(),map=kind==='room'?'room':kind==='leave'?'leave':'detainee',q=d.qr[map]?.[id],x=kind==='room'?d.rooms.find(z=>z.id===id):kind==='leave'?d.leaves.find(z=>z.id===id):d.detainees.find(z=>z.id===id);if(!q||!x||!window.qrcode){toast('QR belum siap untuk dicetak');return}const payload='mta://'+kind+'/'+id+'/'+q.token;const label=kind==='room'?x.block+' / '+x.room:kind==='leave'?x.id+' · '+x.destination:x.code+' · '+x.name;const g=qrcode(0,'M');g.addData(payload);g.make();const svg=g.createSvgTag(8,0);const title='MTA DETENI · QR '+kind.toUpperCase();const w=window.open('','_blank','width=520,height=720');if(!w){toast('Popup diblokir browser. Izinkan popup untuk mencetak QR.');return}w.document.open();w.document.write(`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(title)}</title><style>@page{size:A6 portrait;margin:8mm}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;font-family:"Segoe UI",Arial,sans-serif;color:#111}body{display:flex;justify-content:center}.sheet{width:100%;max-width:105mm;min-height:132mm;display:flex;flex-direction:column;align-items:center;text-align:center;padding:4mm 2mm}.brand{font-size:10pt;font-weight:700;letter-spacing:.03em}.type{font-size:8pt;color:#555;margin-top:2mm;text-transform:uppercase}.qr{width:76mm;height:76mm;margin:7mm auto 5mm;display:flex;align-items:center;justify-content:center}.qr svg{width:76mm!important;height:76mm!important}.label{font-size:15pt;font-weight:700;margin:0 0 2mm;overflow-wrap:anywhere}.status{font-size:9pt;font-weight:700;letter-spacing:.08em;margin-bottom:3mm}.payload{font:7pt ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere;word-break:break-all;max-width:92mm}.note{font-size:7pt;color:#555;margin-top:6mm;border-top:1px solid #ccc;padding-top:3mm;max-width:92mm}.footer{font-size:6.5pt;color:#777;margin-top:auto;padding-top:5mm}</style></head><body><main class="sheet"><div class="brand">MTA DETENI</div><div class="type">${E('QR '+kind)}</div><div class="qr">${svg}</div><div class="label">${E(label)}</div><div class="status">${E(q.status)}</div><div class="payload">${E(payload)}</div><div class="note">Opaque token · QR bukan autentikasi · resolusi tetap melalui policy boundary.</div><div class="footer">Synthetic functional runtime · No operational detainee data</div></main><script>window.onload=()=>setTimeout(()=>window.print(),250);</script></body></html>`);w.document.close();audit('QR_PRINT','QR',id);};
let stream=null;async function camera(r){r.innerHTML=`<section class="hero"><h1>Camera Scan</h1><p class="sub">Scanner QR berbasis kamera perangkat bila browser mendukung BarcodeDetector. Fallback tetap tersedia melalui input manual.</p></section><div class="p6grid"><div class="p6card"><video id="p6video" class="p6video" autoplay playsinline></video><div class="p6row" style="margin-top:10px"><button class="btn primary" onclick="window.p6startCamera()">Start Camera</button><button class="btn" onclick="window.p6stopCamera()">Stop</button></div><p id="p6cammsg" class="p6mini">Camera belum aktif.</p></div><div class="p6card"><h2>Manual fallback</h2><input id="p6manual" class="p6input" placeholder="mta://room/TOKEN"><button class="btn primary" style="margin-top:8px" onclick="window.p6manualScan()">Resolve</button><div id="p6scanout" style="margin-top:12px"></div></div></div>`}
window.p6startCamera=async()=>{const msg=document.querySelector('#p6cammsg');try{if(!('BarcodeDetector'in window)){msg.textContent='BarcodeDetector tidak tersedia. Gunakan manual fallback.';return}stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const v=document.querySelector('#p6video');v.srcObject=stream;const detector=new BarcodeDetector({formats:['qr_code']});msg.textContent='Camera aktif — arahkan ke QR.';const loop=async()=>{if(!stream)return;try{const hits=await detector.detect(v);if(hits[0]?.rawValue){document.querySelector('#p6manual').value=hits[0].rawValue;window.p6manualScan();window.p6stopCamera();return}}catch{}requestAnimationFrame(loop)};requestAnimationFrame(loop)}catch(e){msg.textContent='Camera ditolak/tidak tersedia. Gunakan manual fallback.'}};window.p6stopCamera=()=>{if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}const v=document.querySelector('#p6video');if(v)v.srcObject=null};
window.p6manualScan=()=>{const raw=(document.querySelector('#p6manual')?.value||'').trim(),d=ensure();let hit=null,type='';if(raw.startsWith('mta://detainee/')){type='DETAINEE';hit=Object.entries(d.qr.detainee).find(([,q])=>q.token===raw.split('/').pop())}else if(raw.startsWith('mta://room/')){type='ROOM';hit=Object.entries(d.qr.room).find(([,q])=>q.token===raw.split('/').pop())}else if(raw.startsWith('mta://leave/')){type='LEAVE';hit=Object.entries(d.qr.leave).find(([,q])=>q.token===raw.split('/').pop())}const o=document.querySelector('#p6scanout');if(!hit){o.innerHTML='<div class="notice p6danger">DENIED · token tidak valid.</div>';audit('CAMERA_SCAN_RESOLVE','QR_SCAN',raw,'FAILED');return}o.innerHTML=`<div class="notice"><b>${type}</b> · ${E(hit[1].status)}<br>Resource: ${E(hit[0])}<br><span class="p6mini">Protected projection tetap membutuhkan authentication + RBAC.</span></div>`;audit('CAMERA_SCAN_RESOLVE','QR_SCAN',raw)};
function p6dailyGuardSnapshot(d,date){
  const day=s=>s&&String(s).slice(0,10)===date;
  const activePlacements=d.placements.filter(x=>x.active);
  const occupied=new Set(activePlacements.map(x=>x.roomId||((x.block||'')+'/'+(x.room||''))).filter(Boolean));
  const movements=d.movements.filter(x=>day(x.occurredAt||x.createdAt));
  const leaves=d.leaves.filter(x=>day(x.occurredAt)||day(x.returnedAt));
  const incidents=(d.incidents||[]).filter(x=>day(x.occurredAt||x.createdAt));
  const totals={
    detaineesActive:d.detainees.filter(x=>x.status==='AKTIF').length,
    detaineesTotal:d.detainees.length,
    roomsTotal:d.rooms.length,
    roomsOccupied:occupied.size,
    placementsActive:activePlacements.length,
    movementsToday:movements.length,
    movementsIn:movements.filter(x=>x.type==='IN').length,
    movementsOut:movements.filter(x=>x.type==='OUT').length,
    leavesToday:leaves.length,
    leavesApproved:d.leaves.filter(x=>x.status==='APPROVED'&&day(x.occurredAt)).length,
    leavesReturned:d.leaves.filter(x=>x.status==='RETURNED'&&day(x.returnedAt||x.occurredAt)).length,
    incidentsToday:incidents.length,
    incidentsOpen:incidents.filter(x=>x.status!=='CLOSED').length
  };
  const invalid=Object.values(totals).some(x=>!Number.isInteger(x)||x<0)||totals.roomsOccupied>totals.roomsTotal||totals.placementsActive>totals.detaineesTotal||totals.movementsIn+totals.movementsOut>totals.movementsToday;
  if(invalid) throw new Error('DAILY_GUARD_REPORT_VALIDATION_FAILED');
  return {version:'DGR-v1',reportDate:date,generatedAt:new Date().toISOString(),totals,provenance:'synthetic-operational-runtime'};
}
function reports(r,d){
  const date=new Date().toISOString().slice(0,10);
  let snapshot;
  try{snapshot=p6dailyGuardSnapshot(d,date)}catch(e){r.innerHTML='<div class="notice p6danger">Laporan ditolak: validasi agregasi gagal.</div>';audit('DAILY_GUARD_REPORT_VALIDATE','REPORT','daily','FAILED');return}
  const t=snapshot.totals;
  const rows=[['Deteni aktif',t.detaineesActive],['Deteni total',t.detaineesTotal],['Kamar',t.roomsTotal],['Kamar terisi',t.roomsOccupied],['Penempatan aktif',t.placementsActive],['Pergerakan hari ini',t.movementsToday],['Movement IN',t.movementsIn],['Movement OUT',t.movementsOut],['Izin hari ini',t.leavesToday],['Izin disetujui',t.leavesApproved],['Izin kembali',t.leavesReturned],['Kejadian hari ini',t.incidentsToday],['Kejadian terbuka',t.incidentsOpen]];
  r.innerHTML=\`<section class="hero"><h1>Daily Guard Report</h1><p class="sub">Agregasi data operasional → validasi → laporan. Synthetic runtime; bukan data operasional nyata.</p></section><div class="p6card"><div class="p6row"><b>Tanggal:</b> \${E(snapshot.reportDate)} <span class="p6tag">DGR-v1</span><span class="p6tag">VALIDATED</span></div><div class="tablewrap" style="margin-top:12px"><table class="table"><thead><tr><th>Indikator</th><th>Nilai</th></tr></thead><tbody>\${rows.map(x=>\`<tr><td>\${E(x[0])}</td><td><b>\${x[1]}</b></td></tr>\`).join('')}</tbody></table></div><div class="p6row" style="margin-top:12px"><button class="btn primary" onclick="window.p6csv()">Export CSV</button><button class="btn" onclick="window.p6printReport()">Print / PDF</button></div></div>\`;
  audit('DAILY_GUARD_REPORT_VALIDATE','REPORT',snapshot.reportDate);
  audit('DAILY_GUARD_REPORT_RENDER','REPORT',snapshot.reportDate);
}
window.p6csv=()=>{
  const d=ensure(),date=new Date().toISOString().slice(0,10);let s;
  try{s=p6dailyGuardSnapshot(d,date)}catch(e){audit('DAILY_GUARD_REPORT_EXPORT','REPORT',date,'DENIED');toast('Export ditolak: validasi gagal');return}
  const t=s.totals,rows=[['MTA DETENI','DAILY GUARD REPORT'],['Report Date',s.reportDate],['Generated',s.generatedAt],...Object.entries(t)];
  const csv=rows.map(x=>x.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\\n');
  const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='mta-deteni-daily-guard-report-'+date+'.csv';a.click();
  audit('DAILY_GUARD_REPORT_EXPORT','REPORT',date);toast('Daily Guard Report CSV dibuat');
};
window.p6printReport=()=>{const d=ensure(),date=new Date().toISOString().slice(0,10);try{const s=p6dailyGuardSnapshot(d,date);audit('DAILY_GUARD_REPORT_PRINT','REPORT',date);const t=s.totals;const w=window.open('','_blank','width=800,height=900');if(!w){toast('Popup diblokir browser.');return}w.document.write('<!doctype html><html><head><title>MTA DETENI Daily Guard Report</title><style>body{font-family:Segoe UI,Arial;padding:28px}h1{margin-bottom:4px}table{border-collapse:collapse;width:100%;margin-top:20px}td,th{border:1px solid #ccc;padding:8px;text-align:left}</style></head><body><h1>MTA DETENI — Daily Guard Report</h1><div>Tanggal: '+E(s.reportDate)+' · '+E(s.version)+'</div><table><tbody>'+Object.entries(t).map(([k,v])=>'<tr><td>'+E(k)+'</td><td><b>'+v+'</b></td></tr>').join('')+'</tbody></table><p>Provenance: synthetic-operational-runtime</p><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>');w.document.close()}catch(e){audit('DAILY_GUARD_REPORT_PRINT','REPORT',date,'DENIED');toast('Print ditolak: validasi gagal')}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();