(()=>{
const K='mta-deteni-demo-v2';
const get=()=>window.MTADeteniStateKernel?window.MTADeteniStateKernel.read():JSON.parse(localStorage.getItem(K)||'{}');
const QR_ROOM_STATE='QR_ROOM_STATE';
const put=d=>{const kernel=window.MTADeteniStateKernel;if(!kernel)throw new Error('CANONICAL_STATE_KERNEL_REQUIRED');const result=kernel.write(d);window.dispatchEvent(new CustomEvent('mta:data-changed',{detail:{source:'room-ops-v9'}}));return result};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>p+'-'+crypto.randomUUID().slice(0,10).toUpperCase();
const now=()=>new Date().toISOString();
const appendAudit=(d,a,t,i,r='SUCCESS')=>{const kernel=window.MTADeteniStateKernel;if(kernel?.audit)return kernel.audit(d,a,t,i,r,{actor:'DEMO-OPERATOR'});throw new Error('CANONICAL_AUDIT_KERNEL_REQUIRED')};
function currentPlacement(d,id){return (d.placements||[]).filter(p=>p.detaineeId===id).sort((a,b)=>String(b.since||'').localeCompare(String(a.since||'')))[0]||null}
function occupancy(d,room){return (d.detainees||[]).filter(x=>x.status==='AKTIF').filter(x=>{const p=currentPlacement(d,x.id);return (p&&p.roomId===room.id)||(p&&!p.roomId&&p.block===room.block&&p.room===room.room)}).length}
function activeResidents(d,room){return (d.detainees||[]).filter(x=>x.status==='AKTIF').filter(x=>{const p=currentPlacement(d,x.id);return (p&&p.roomId===room.id)||(p&&!p.roomId&&p.block===room.block&&p.room===room.room)})}
function ensure(){const d=structuredClone(get());d.detainees=Array.isArray(d.detainees)?d.detainees:[];d.placements=Array.isArray(d.placements)?d.placements:[];d.rooms=Array.isArray(d.rooms)?d.rooms:[];d.blocks=Array.isArray(d.blocks)?d.blocks:[];d.qr=d.qr&&typeof d.qr==='object'?d.qr:{detainee:{},room:{},leave:{}};d.qr.room=d.qr.room||{};d.rooms.forEach(r=>{if(!r.blockId){const b=d.blocks.find(b=>String(b.name).toLowerCase()===String(r.block).toLowerCase());if(b)r.blockId=b.id}if(!d.qr.room[r.id])d.qr.room[r.id]={token:'SYNTH-QR-'+r.id,status:r.status==='ACTIVE'?'ACTIVE':'SUSPENDED'}});return d}
function roomQrPayload(d,id){const q=d.qr?.room?.[id];return q?.token?('mta://room/'+id+'/'+q.token):null}
async function roomQrSvg(payload){if(typeof window.qrcode!=='function'){await new Promise(resolve=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/qrcode-generator/1.4.4/qrcode.min.js';s.async=true;s.onload=resolve;s.onerror=resolve;document.head.appendChild(s)})}if(typeof window.qrcode!=='function')return '';const qr=window.qrcode(0,'M');qr.addData(payload);qr.make();return qr.createSvgTag(6,0)}
function closeRoomQr(){document.getElementById('mtaRoomQrModal')?.remove()}
function showRoomQr(id){const d=ensure(),room=d.rooms.find(r=>r.id===id);if(!room){toast('Kamar tidak ditemukan.');return}const residents=activeResidents(d,room),cap=Math.max(0,Number(room.capacity)||0),occ=residents.length,q=d.qr.room[id]||{},payload=roomQrPayload(d,id);const modal=document.createElement('div');modal.id='mtaRoomQrModal';modal.innerHTML='<div class="mta-roomqr-backdrop" data-close="1"><article class="mta-roomqr-card" role="dialog" aria-modal="true" aria-label="Room Operational Detail"><header><div><span class="mta-roomqr-kicker">PERMANENT ROOM QR</span><h2>'+E(room.block)+' · '+E(room.room)+'</h2><p>QR permanen mengidentifikasi lokasi. Penghuni selalu diambil dari placement aktif.</p></div><button class="btn small" data-close="1">×</button></header><div class="mta-roomqr-grid"><section class="mta-roomqr-qr"><div id="mtaRoomQrCode" class="mta-roomqr-code"><span>Memuat QR…</span></div><code>'+E(payload||'QR belum tersedia')+'</code><small>QR ID: '+E(id)+'</small></section><section class="mta-roomqr-summary"><div><small>STATUS KAMAR</small><strong>'+E(room.status||'ACTIVE')+'</strong></div><div><small>KAPASITAS</small><strong>'+occ+' / '+(cap||'—')+'</strong></div><div><small>TERSEDIA</small><strong>'+Math.max(0,cap-occ)+'</strong></div><div><small>QR STATE</small><strong>'+E(q.status||'ACTIVE')+'</strong></div></section></div><section class="mta-roomqr-residents"><div class="mta-roomqr-section-head"><div><span class="mta-roomqr-kicker">PLACEMENT AKTIF</span><h3>Deteni yang saat ini menghuni kamar</h3></div><span>'+residents.length+' penghuni</span></div>'+(residents.length?'<div class="mta-roomqr-resident-list">'+residents.map(x=>'<button class="mta-roomqr-resident" data-detainee="'+E(x.id)+'"><b>'+E(x.nid||x.code||x.id)+'</b><span>'+E(x.name)+'</span><small>'+E(x.nationality||'—')+' · '+E(x.status||'—')+'</small></button>').join('')+'</div>':'<div class="mta-roomqr-empty">Belum ada deteni aktif pada kamar ini.</div>')+'</section><footer><span>Source of truth: Master Room + Placement Aktif</span><button class="btn" data-close="1">Tutup</button></footer></article></div>';document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target.dataset.close)return closeRoomQr();const b=e.target.closest('[data-detainee]');if(b){closeRoomQr();window.show?.('detainee-detail',b.dataset.detainee)}});roomQrSvg(payload).then(svg=>{const el=document.getElementById('mtaRoomQrCode');if(el)el.innerHTML=svg||'<span>QR engine belum tersedia.</span>'});}
function render(){const r=document.querySelector('#appView');if(!r)return;const d=ensure();const known=new Set(d.rooms.map(x=>x.id));const orphan=(d.placements||[]).filter(p=>p.roomId&&!known.has(p.roomId));const rows=d.rooms.map(x=>{const occ=occupancy(d,x),cap=Math.max(0,Number(x.capacity)||0),q=d.qr.room[x.id]||{status:'ACTIVE',token:''};const roomState=x.status||'ACTIVE',qrState=q.status||'ACTIVE',full=cap>0&&occ>=cap;return '<tr><td><b>'+E(x.block)+'</b></td><td>'+E(x.room)+'</td><td>'+occ+'/'+(cap||'—')+(full?' · FULL':'')+'</td><td><span class="p6tag">'+E(roomState)+'</span></td><td><span class="p6tag">'+E(qrState)+'</span></td><td><button class="btn small primary" onclick="window.p6qr(\'room\',\''+E(x.id)+'\')">QR</button> <button class="btn small" onclick="window.p9roomQrState(\''+E(x.id)+'\')">QR State</button></td></tr>'}).join('');const warnings=orphan.length?'<div class="notice p6danger" style="margin-top:12px"><b>'+orphan.length+' placement legacy/orphan terdeteksi.</b> Tidak dibuatkan kamar otomatis. Administrator harus memetakan placement tersebut ke Master Kamar sebelum persistence production dibuka.</div>':'';r.innerHTML='<section class="hero"><h1>Room Operations</h1><p class="sub">Monitoring kamar yang terdaftar oleh Administrator. Room Ops tidak membuat master kamar.</p></section><div class="p6grid"><div class="p6card"><h2>Room Summary</h2><div class="kpis"><div><div class="label">Total Kamar</div><b>'+d.rooms.length+'</b></div><div><div class="label">Kamar Terisi</div><b>'+d.rooms.filter(x=>occupancy(d,x)>0).length+'</b></div><div><div class="label">Kapasitas</div><b>'+d.rooms.reduce((n,x)=>n+(Number(x.capacity)||0),0)+'</b></div></div></div><div class="p6card"><h2>Governance</h2><p class="p6mini">Master data: Pengaturan Administrator → Master Blok/Kamar. Room Ops hanya membaca master dan menjalankan lifecycle QR.</p></div></div><div class="p6card" style="margin-top:12px"><div class="tablewrap"><table class="table"><thead><tr><th>Blok</th><th>Kamar</th><th>Occupancy</th><th>Room State</th><th>QR State</th><th>Aksi</th></tr></thead><tbody>'+ (rows||'<tr><td colspan="6" class="empty">Belum ada master kamar.</td></tr>')+'</tbody></table></div>'+warnings+'</div>'}
window.p6qr=(kind,id)=>{if(kind==='room')return showRoomQr(id);if(typeof window.mtaUnifiedAction==='function')return window.mtaUnifiedAction(kind,id);toast('QR action belum tersedia.')};
window.p9roomQrState=async id=>{const d=ensure();if(!window.MTADeteniDomainCommandsV2){toast('Canonical QR command belum siap.');return}const result=await window.MTADeteniDomainCommandsV2.roomQrState(d,id);if(!result?.ok){toast('Room QR ditolak: '+(result?.code||'MUTATION_FAILED'));return}if(window.mtaProductionStateAdapter?.isProduction?.()){toast('Room QR state tersimpan ke database: '+result.qr.status);render()}else{if(!put(d))return;toast('Room QR state → '+result.qr.status);render()}};
window.p9refreshRooms=()=>{ensure();render();toast('Room Ops diperbarui.')};
window.MTARoomOpsView=Object.freeze({render,ensure,showRoomQr});
ensure();
})();