(()=>{
const K='mta-deteni-demo-v2';
const get=()=>JSON.parse(localStorage.getItem(K)||'{}');
const put=d=>{localStorage.setItem(K,JSON.stringify(d));window.dispatchEvent(new CustomEvent('mta:data-changed'))};
const E=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>p+'-'+crypto.randomUUID().slice(0,10).toUpperCase();
const now=()=>new Date().toISOString();
const appendAudit=(d,a,t,i,r='SUCCESS')=>{d.audit=d.audit||[];d.audit.unshift({id:uid('AUD'),action:a,resourceType:t,resourceId:i||'',result:r,occurredAt:new Date().toISOString(),actor:'DEMO-OPERATOR',requestId:uid('REQ'),correlationId:uid('COR'),policyVersion:'AUTHZ-1.0'})};
function currentPlacement(d,id){return (d.placements||[]).filter(p=>p.detaineeId===id).sort((a,b)=>String(b.since||'').localeCompare(String(a.since||'')))[0]||null}
function occupancy(d,room){return (d.detainees||[]).filter(x=>x.status==='AKTIF').filter(x=>{const p=currentPlacement(d,x.id);return (p&&p.roomId===room.id)||(p&&!p.roomId&&p.block===room.block&&p.room===room.room)}).length}
function ensure(){const d=get();d.detainees=d.detainees||[];d.placements=d.placements||[];d.rooms=d.rooms||[];d.blocks=d.blocks||[];d.qr=d.qr||{detainee:{},room:{},leave:{}};d.qr.room=d.qr.room||{};let changed=false;d.rooms.forEach(r=>{if(!r.blockId){const b=d.blocks.find(b=>String(b.name).toLowerCase()===String(r.block).toLowerCase());if(b){r.blockId=b.id;changed=true}}if(!d.qr.room[r.id]){d.qr.room[r.id]={token:uid('RMQR'),status:'ACTIVE'};changed=true}});if(changed)put(d);return d}
function render(){const r=document.querySelector('#appView');if(!r)return;const d=ensure();const known=new Set(d.rooms.map(x=>x.id));const orphan=(d.placements||[]).filter(p=>p.roomId&&!known.has(p.roomId));const rows=d.rooms.map(x=>{const occ=occupancy(d,x),cap=Math.max(0,Number(x.capacity)||0),q=d.qr.room[x.id]||{status:'ACTIVE',token:''};const roomState=x.status||'ACTIVE',qrState=q.status||'ACTIVE',full=cap>0&&occ>=cap;return `<tr><td><b>${E(x.block)}</b></td><td>${E(x.room)}</td><td>${occ}/${cap||'—'}${full?' · FULL':''}</td><td><span class="p6tag">${E(roomState)}</span></td><td><span class="p6tag">${E(qrState)}</span></td><td><button class="btn small" onclick="window.p6qr('room','${E(x.id)}')">QR</button> <button class="btn small" onclick="window.p9roomQrState('${E(x.id)}')">QR State</button></td></tr>`}).join('');const warnings=orphan.length?`<div class="notice p6danger" style="margin-top:12px"><b>${orphan.length} placement legacy/orphan terdeteksi.</b> Tidak dibuatkan kamar otomatis. Administrator harus memetakan placement tersebut ke Master Kamar sebelum persistence production dibuka.</div>`:'';r.innerHTML=`<section class="hero"><h1>Room Operations</h1><p class="sub">Monitoring kamar yang terdaftar oleh Administrator. Room Ops tidak membuat master kamar.</p></section><div class="p6grid"><div class="p6card"><h2>Room Summary</h2><div class="kpis"><div><div class="label">Total Kamar</div><b>${d.rooms.length}</b></div><div><div class="label">Kamar Terisi</div><b>${d.rooms.filter(x=>occupancy(d,x)>0).length}</b></div><div><div class="label">Kapasitas</div><b>${d.rooms.reduce((n,x)=>n+(Number(x.capacity)||0),0)}</b></div></div></div><div class="p6card"><h2>Governance</h2><p class="p6mini">Master data: Pengaturan Administrator → Master Blok/Kamar. Room Ops hanya membaca master dan menjalankan lifecycle QR.</p></div></div><div class="p6card" style="margin-top:12px"><div class="tablewrap"><table class="table"><thead><tr><th>Blok</th><th>Kamar</th><th>Occupancy</th><th>Room State</th><th>QR State</th><th>Aksi</th></tr></thead><tbody>${rows||'<tr><td colspan="6" class="empty">Belum ada master kamar.</td></tr>'}</tbody></table></div>${warnings}</div>`}
window.p9roomQrState=id=>{const d=ensure(),x=d.rooms.find(z=>z.id===id),q=d.qr.room[id];if(!x||!q)return;const next={ACTIVE:'SUSPENDED',SUSPENDED:'REVOKED',REVOKED:'ACTIVE'}[q.status]||'ACTIVE';q.status=next;appendAudit(d,'QR_ROOM_STATE_CHANGE','ROOM_QR',id);d.lastMutation={key:'QR_ROOM_STATE:'+id+':'+next,action:'QR_ROOM_STATE_CHANGE',completedAt:now()};put(d);toast('Room QR state → '+next);render()};
window.p9refreshRooms=()=>{ensure();render();toast('Room Ops diperbarui.')};
const oldShow=window.show;window.show=v=>v==='p9rooms'?render():v==='p6rooms'?render():oldShow(v);
const nav=document.querySelector('#nav');if(nav&&!document.querySelector('#p9rooms')){const b=document.createElement('button');b.id='p9rooms';b.dataset.view='p9rooms';b.textContent='Room Ops';b.onclick=()=>window.show('p9rooms');nav.appendChild(b)}
ensure();
})();
